//! Answering the imports `sdl.wasm` and `ui.wasm` declare.
//!
//! GENERATED by `scripts/generate_sdl_shim.py --host` from the signatures
//! `sdl.hdll` reports for itself, so this side and the library's side cannot
//! disagree about an argument. Edit the generator, not this file.
//!
//! Every binding funnels into [`super::sdl::Sdl::call`], which is where a
//! window and a frame are actually decided. Nothing is decided here.

use wasmtime::{Caller, Linker};

use super::sdl::Arg;
use super::{Host, FIBER_YIELD_MODULE};

/// Install all sixty-seven.
pub(crate) fn install(linker: &mut Linker<Host>) -> anyhow::Result<()> {
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_cursor_create",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| -> i32 { caller.data_mut().sdl.call("sdl@cursor_create", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_cursor_create_system",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@cursor_create_system", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_delay",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@delay", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_detect_keyboard_layout",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@detect_keyboard_layout", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_detect_win32",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@detect_win32", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_event_loop",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@event_loop", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_free_cursor",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@free_cursor", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_free_surface",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@free_surface", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gctrl_close",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gctrl_close", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gctrl_count",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gctrl_count", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gctrl_get_axis",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@gctrl_get_axis", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gctrl_get_button",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@gctrl_get_button", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gctrl_get_id",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@gctrl_get_id", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gctrl_get_name",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@gctrl_get_name", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gctrl_open",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@gctrl_open", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_clipboard_text",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@get_clipboard_text", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_current_display_mode",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@get_current_display_mode", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_devices",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@get_devices", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_display_modes",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@get_display_modes", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_displays",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@get_displays", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_drag_and_drop_enabled",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@get_drag_and_drop_enabled", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_framerate",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@get_framerate", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_global_mouse_state",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@get_global_mouse_state", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_relative_mouse_mode",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@get_relative_mouse_mode", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_screen_height",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@get_screen_height", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_screen_height_of_window",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@get_screen_height_of_window", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_screen_width",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@get_screen_width", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_screen_width_of_window",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@get_screen_width_of_window", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_get_window_grab",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@get_window_grab", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_active_texture",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_active_texture", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_attach_shader",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_attach_shader", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_begin_query",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_begin_query", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_bind_buffer",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_bind_buffer", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_bind_buffer_base",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@gl_bind_buffer_base", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_bind_frag_data_location",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a2_len: i32| { caller.data_mut().sdl.call("sdl@gl_bind_frag_data_location", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a2_len)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_bind_framebuffer",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_bind_framebuffer", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_bind_image_texture",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32| { caller.data_mut().sdl.call("sdl@gl_bind_image_texture", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_bind_renderbuffer",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_bind_renderbuffer", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_bind_texture",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_bind_texture", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_bind_vertex_array",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_bind_vertex_array", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_blend_equation",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_blend_equation", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_blend_equation_separate",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_blend_equation_separate", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_blend_func",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_blend_func", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_blend_func_separate",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_blend_func_separate", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_blit_framebuffer",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32| { caller.data_mut().sdl.call("sdl@gl_blit_framebuffer", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7), Arg::I(a8), Arg::I(a9)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_buffer_data",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_buffer_data", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_buffer_data_size",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@gl_buffer_data_size", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_buffer_sub_data",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_buffer_sub_data", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_clear",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_clear", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_clear_color",
        |mut caller: Caller<'_, Host>, a0: f64, a1: f64, a2: f64, a3: f64| { caller.data_mut().sdl.call("sdl@gl_clear_color", &[Arg::D(a0), Arg::D(a1), Arg::D(a2), Arg::D(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_clear_depth",
        |mut caller: Caller<'_, Host>, a0: f64| { caller.data_mut().sdl.call("sdl@gl_clear_depth", &[Arg::D(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_clear_stencil",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_clear_stencil", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_color_mask",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_color_mask", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_color_maski",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_color_maski", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_compile_shader",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_compile_shader", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_compressed_tex_image2d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32| { caller.data_mut().sdl.call("sdl@gl_compressed_tex_image2d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_compressed_tex_image3d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32| { caller.data_mut().sdl.call("sdl@gl_compressed_tex_image3d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7), Arg::I(a8)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_compressed_tex_sub_image2d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32| { caller.data_mut().sdl.call("sdl@gl_compressed_tex_sub_image2d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7), Arg::I(a8)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_compressed_tex_sub_image3d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32, a10: i32| { caller.data_mut().sdl.call("sdl@gl_compressed_tex_sub_image3d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7), Arg::I(a8), Arg::I(a9), Arg::I(a10)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_create_buffer",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_create_buffer", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_create_framebuffer",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_create_framebuffer", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_create_program",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_create_program", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_create_query",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_create_query", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_create_renderbuffer",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_create_renderbuffer", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_create_shader",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_create_shader", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_create_texture",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_create_texture", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_create_vertex_array",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_create_vertex_array", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_cull_face",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_cull_face", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_delete_buffer",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_delete_buffer", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_delete_framebuffer",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_delete_framebuffer", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_delete_query",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_delete_query", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_delete_renderbuffer",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_delete_renderbuffer", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_delete_shader",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_delete_shader", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_delete_texture",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_delete_texture", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_delete_vertex_array",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_delete_vertex_array", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_depth_func",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_depth_func", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_depth_mask",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_depth_mask", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_disable",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_disable", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_disable_vertex_attrib_array",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_disable_vertex_attrib_array", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_dispatch_compute",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@gl_dispatch_compute", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_draw_arrays",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@gl_draw_arrays", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_draw_arrays_instanced",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_draw_arrays_instanced", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_draw_buffers",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_draw_buffers", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_draw_elements",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_draw_elements", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_draw_elements_instanced",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_draw_elements_instanced", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_enable",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_enable", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_enable_vertex_attrib_array",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_enable_vertex_attrib_array", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_end_query",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_end_query", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_finish",
        |mut caller: Caller<'_, Host>| { caller.data_mut().sdl.call("sdl@gl_finish", &[]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_framebuffer_renderbuffer",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_framebuffer_renderbuffer", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_framebuffer_texture",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_framebuffer_texture", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_framebuffer_texture2d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_framebuffer_texture2d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_framebuffer_texture_layer",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_framebuffer_texture_layer", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_generate_mipmap",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_generate_mipmap", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_attrib_location",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a1_len: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_attrib_location", &[Arg::I(a0), Arg::I(a1), Arg::I(a1_len)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_config_parameter",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_config_parameter", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_error",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_error", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_program_info_bytes",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_program_info_bytes", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_program_parameter",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_program_parameter", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_program_resource_index",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a2_len: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_program_resource_index", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a2_len)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_shader_info_bytes",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_shader_info_bytes", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_shader_parameter",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_shader_parameter", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_uniform_block_index",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a1_len: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_uniform_block_index", &[Arg::I(a0), Arg::I(a1), Arg::I(a1_len)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_get_uniform_location",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a1_len: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_get_uniform_location", &[Arg::I(a0), Arg::I(a1), Arg::I(a1_len)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_has_extension",
        |mut caller: Caller<'_, Host>, a0: i32, a0_len: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_has_extension", &[Arg::I(a0), Arg::I(a0_len)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_init",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_init", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_is_context_lost",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@gl_is_context_lost", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_link_program",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_link_program", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_memory_barrier",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_memory_barrier", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_multi_draw_elements_indirect",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_multi_draw_elements_indirect", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_multi_draw_elements_indirect_count",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32| { caller.data_mut().sdl.call("sdl@gl_multi_draw_elements_indirect_count", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_options",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32| { caller.data_mut().sdl.call("sdl@gl_options", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_pixel_storei",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_pixel_storei", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_polygon_mode",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_polygon_mode", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_polygon_offset",
        |mut caller: Caller<'_, Host>, a0: f64, a1: f64| { caller.data_mut().sdl.call("sdl@gl_polygon_offset", &[Arg::D(a0), Arg::D(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_query_counter",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_query_counter", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_query_result",
        |mut caller: Caller<'_, Host>, a0: i32| -> f64 { f64::from_bits(caller.data_mut().sdl.call("sdl@gl_query_result", &[Arg::I(a0)]) as u64) },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_query_result_available",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@gl_query_result_available", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_read_buffer",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_read_buffer", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_read_pixels",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32| { caller.data_mut().sdl.call("sdl@gl_read_pixels", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_renderbuffer_storage",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_renderbuffer_storage", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_renderbuffer_storage_multisample",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_renderbuffer_storage_multisample", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_scissor",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_scissor", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_shader_source",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a1_len: i32| { caller.data_mut().sdl.call("sdl@gl_shader_source", &[Arg::I(a0), Arg::I(a1), Arg::I(a1_len)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_shader_storage_block_binding",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@gl_shader_storage_block_binding", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_stencil_func_separate",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_stencil_func_separate", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_stencil_mask_separate",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_stencil_mask_separate", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_stencil_op_separate",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_stencil_op_separate", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_tex_image2d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32| { caller.data_mut().sdl.call("sdl@gl_tex_image2d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7), Arg::I(a8)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_tex_image2d_multisample",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32| { caller.data_mut().sdl.call("sdl@gl_tex_image2d_multisample", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_tex_image3d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32| { caller.data_mut().sdl.call("sdl@gl_tex_image3d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7), Arg::I(a8), Arg::I(a9)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_tex_parameterf",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: f64| { caller.data_mut().sdl.call("sdl@gl_tex_parameterf", &[Arg::I(a0), Arg::I(a1), Arg::D(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_tex_parameteri",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@gl_tex_parameteri", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_tex_storage2d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_tex_storage2d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_tex_storage3d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32| { caller.data_mut().sdl.call("sdl@gl_tex_storage3d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_tex_sub_image2d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32| { caller.data_mut().sdl.call("sdl@gl_tex_sub_image2d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7), Arg::I(a8)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_tex_sub_image3d",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32, a10: i32| { caller.data_mut().sdl.call("sdl@gl_tex_sub_image3d", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7), Arg::I(a8), Arg::I(a9), Arg::I(a10)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_uniform1i",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_uniform1i", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_uniform4fv",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_uniform4fv", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_uniform_block_binding",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@gl_uniform_block_binding", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_uniform_matrix4fv",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_uniform_matrix4fv", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_use_program",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@gl_use_program", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_vertex_attrib_divisor",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@gl_vertex_attrib_divisor", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_vertex_attrib_ipointer",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| { caller.data_mut().sdl.call("sdl@gl_vertex_attrib_ipointer", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_vertex_attrib_pointer",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32| { caller.data_mut().sdl.call("sdl@gl_vertex_attrib_pointer", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_gl_viewport",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| { caller.data_mut().sdl.call("sdl@gl_viewport", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_haptic_close",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@haptic_close", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_haptic_open",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@haptic_open", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_haptic_rumble_init",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@haptic_rumble_init", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_haptic_rumble_play",
        |mut caller: Caller<'_, Host>, a0: i32, a1: f64, a2: i32| -> i32 { caller.data_mut().sdl.call("sdl@haptic_rumble_play", &[Arg::I(a0), Arg::D(a1), Arg::I(a2)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_hint_value",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@hint_value", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_init_once",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@init_once", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_is_cursor_visible",
        |mut caller: Caller<'_, Host>| -> i32 { caller.data_mut().sdl.call("sdl@is_cursor_visible", &[]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_message_box",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@message_box", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_quit",
        |mut caller: Caller<'_, Host>| { caller.data_mut().sdl.call("sdl@quit", &[]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_set_clipboard_text",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@set_clipboard_text", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_set_cursor",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@set_cursor", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_set_drag_and_drop_enabled",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@set_drag_and_drop_enabled", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_set_relative_mouse_mode",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@set_relative_mouse_mode", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_set_vsync",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@set_vsync", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_set_window_grab",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@set_window_grab", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_show_cursor",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("sdl@show_cursor", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_surface_from",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32| -> i32 { caller.data_mut().sdl.call("sdl@surface_from", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4), Arg::I(a5), Arg::I(a6), Arg::I(a7), Arg::I(a8)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_warp_mouse_global",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@warp_mouse_global", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_warp_mouse_in_window",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@warp_mouse_in_window", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_create",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@win_create", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_create_ex",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32, a4: i32| -> i32 { caller.data_mut().sdl.call("sdl@win_create_ex", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3), Arg::I(a4)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_destroy",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@win_destroy", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_display_handle",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@win_display_handle", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_get_glcontext",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@win_get_glcontext", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_get_id",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("sdl@win_get_id", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_get_max_size",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@win_get_max_size", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_get_min_size",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@win_get_min_size", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_get_opacity",
        |mut caller: Caller<'_, Host>, a0: i32| -> f64 { f64::from_bits(caller.data_mut().sdl.call("sdl@win_get_opacity", &[Arg::I(a0)]) as u64) },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_get_position",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@win_get_position", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_get_size",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@win_get_size", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_render_to",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@win_render_to", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_resize",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@win_resize", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_set_display_mode",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32, a3: i32| -> i32 { caller.data_mut().sdl.call("sdl@win_set_display_mode", &[Arg::I(a0), Arg::I(a1), Arg::I(a2), Arg::I(a3)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_set_fullscreen",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("sdl@win_set_fullscreen", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_set_max_size",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@win_set_max_size", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_set_min_size",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@win_set_min_size", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_set_opacity",
        |mut caller: Caller<'_, Host>, a0: i32, a1: f64| -> i32 { caller.data_mut().sdl.call("sdl@win_set_opacity", &[Arg::I(a0), Arg::D(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_set_position",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@win_set_position", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_set_size",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("sdl@win_set_size", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_sdl_win_set_title",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("sdl@win_set_title", &[Arg::I(a0), Arg::I(a1)]); },
    )?;

    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_button_new",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| -> i32 { caller.data_mut().sdl.call("ui@ui_button_new", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_choose_file",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| -> i32 { caller.data_mut().sdl.call("ui@ui_choose_file", &[Arg::I(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_dialog",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| -> i32 { caller.data_mut().sdl.call("ui@ui_dialog", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_init",
        |mut caller: Caller<'_, Host>| { caller.data_mut().sdl.call("ui@ui_init", &[]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_loop",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("ui@ui_loop", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_sentinel_is_paused",
        |mut caller: Caller<'_, Host>, a0: i32| -> i32 { caller.data_mut().sdl.call("ui@ui_sentinel_is_paused", &[Arg::I(a0)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_sentinel_pause",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32| { caller.data_mut().sdl.call("ui@ui_sentinel_pause", &[Arg::I(a0), Arg::I(a1)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_sentinel_tick",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("ui@ui_sentinel_tick", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_start_sentinel",
        |mut caller: Caller<'_, Host>, a0: f64, a1: i32| -> i32 { caller.data_mut().sdl.call("ui@ui_start_sentinel", &[Arg::D(a0), Arg::I(a1)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_stop_loop",
        |mut caller: Caller<'_, Host>| { caller.data_mut().sdl.call("ui@ui_stop_loop", &[]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_win_destroy",
        |mut caller: Caller<'_, Host>, a0: i32| { caller.data_mut().sdl.call("ui@ui_win_destroy", &[Arg::I(a0)]); },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_winlog_new",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| -> i32 { caller.data_mut().sdl.call("ui@ui_winlog_new", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]) as i32 },
    )?;
    linker.func_wrap(
        FIBER_YIELD_MODULE,
        "ash_host_ui_ui_winlog_set_text",
        |mut caller: Caller<'_, Host>, a0: i32, a1: i32, a2: i32| { caller.data_mut().sdl.call("ui@ui_winlog_set_text", &[Arg::I(a0), Arg::I(a1), Arg::I(a2)]); },
    )?;
    Ok(())
}
