use std::fmt::Write as _;
use std::{env, fs, path::PathBuf};

/// The most arguments a generated signature covers.
///
/// Both calling conventions we target pass this many in registers, and no
/// primitive in the tree comes close.
const MAX_ARGS: u32 = 8;

/// Above this many arguments, only signatures whose floats are all the same
/// type are generated.
///
/// Three states per argument all the way to eight is 29,523 signatures, which
/// killed rustc for out of memory on a machine with sixteen gigabytes. Mixing
/// `f32` and `f64` in one call is the part that is dropped, and only past five
/// arguments: HL has both types but a function's floats are almost always one
/// or the other.
const MAX_MIXED_ARGS: u32 = 5;

#[derive(Clone, Copy, PartialEq)]
enum Kind {
    Int,
    F32,
    F64,
}

impl Kind {
    fn rust(self) -> &'static str {
        match self {
            Kind::Int => "i64",
            Kind::F32 => "f32",
            Kind::F64 => "f64",
        }
    }
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let kinds = [Kind::Int, Kind::F32, Kind::F64];
    let mut out = String::from(
        "// GENERATED by build.rs. Edit the generator, not this file.\n\n",
    );
    let mut arms = String::new();
    let mut count = 0usize;

    for arity in 0..=MAX_ARGS {
        for pattern in 0..3usize.pow(arity) {
            let mut at = pattern;
            let mut args = Vec::new();
            for _ in 0..arity {
                args.push(kinds[at % 3]);
                at /= 3;
            }
            // Past MAX_MIXED_ARGS only uniform float signatures are emitted.
            let mixed = args.contains(&Kind::F32) && args.contains(&Kind::F64);
            if arity > MAX_MIXED_ARGS && mixed {
                continue;
            }
            for (ret_code, ret) in kinds.iter().enumerate() {
                let params = args.iter().map(|k| k.rust()).collect::<Vec<_>>().join(", ");
                let values = args
                    .iter()
                    .enumerate()
                    .map(|(i, k)| match k {
                        Kind::Int => format!("ints[{i}]"),
                        Kind::F32 => format!("f32s[{i}]"),
                        Kind::F64 => format!("f64s[{i}]"),
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                let call = match ret {
                    Kind::Int => format!("f({values})"),
                    Kind::F32 => format!("(f({values}) as f64).to_bits() as i64"),
                    Kind::F64 => format!("f({values}).to_bits() as i64"),
                };
                let _ = write!(
                    arms,
                    "        ({arity}, {ret_code}, {pattern}) => {{\n\
                     \x20           let f: unsafe extern \"C\" fn({params}) -> {} =\n\
                     \x20               std::mem::transmute(func_ptr);\n\
                     \x20           {call}\n\
                     \x20       }}\n",
                    ret.rust()
                );
                count += 1;
            }
        }
    }

    let _ = write!(
        out,
        "/// The number of signatures below, which a test asserts.\n\
         pub const SIGNATURES: usize = {count};\n\n\
         /// Call `func_ptr` as the signature the kinds describe.\n\
         ///\n\
         /// `ints`, `f32s` and `f64s` are each as long as the argument list;\n\
         /// `arg_kinds` says which to read at every position, as 0 integer,\n\
         /// 1 f32, 2 f64. `ret_kind` is the same three for the return, and a\n\
         /// float comes back as its bits.\n\
         ///\n\
         /// `None` if this signature was not generated: see `build.rs`.\n\
         ///\n\
         /// # Safety\n\
         /// `func_ptr` must be a function of exactly that signature.\n\
         pub unsafe fn dispatch(\n\
         \x20   func_ptr: *mut std::ffi::c_void,\n\
         \x20   ints: &[i64],\n\
         \x20   f32s: &[f32],\n\
         \x20   f64s: &[f64],\n\
         \x20   arg_kinds: &[u8],\n\
         \x20   ret_kind: u8,\n\
         ) -> Option<i64> {{\n\
         \x20   // One number for the whole argument list, least significant\n\
         \x20   // digit first, so the match below is a jump and not a walk.\n\
         \x20   let mut pattern: u32 = 0;\n\
         \x20   for &k in arg_kinds.iter().rev() {{\n\
         \x20       pattern = pattern * 3 + k as u32;\n\
         \x20   }}\n\
         \x20   Some(match (arg_kinds.len(), ret_kind, pattern) {{\n{arms}\
         \x20       _ => return None,\n\
         \x20   }})\n\
         }}\n"
    );

    let path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("dispatch.rs");
    fs::write(path, out).expect("writing the dispatch table");
}
