use std::fmt::Write as _;
use std::{env, fs, path::PathBuf};

/// The most arguments a generated signature covers.
///
/// The interpreter's mixed-float native dispatch is generated through this arity.
const MAX_ARGS: usize = 8;
const CHUNK_SIZE: usize = 256;

#[derive(Clone, Copy)]
enum Kind {
    Int,
    F32,
    F64,
}

impl Kind {
    fn rust(self) -> &'static str {
        match self {
            Kind::Int => "i64",
            Kind::F32 => "f32",
            Kind::F64 => "f64",
        }
    }
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let kinds = [Kind::Int, Kind::F32, Kind::F64];
    let mut out = String::from("// GENERATED by build.rs. Edit the generator, not this file.\n\n");
    let count = (0..=MAX_ARGS)
        .map(|arity| 3usize.pow(arity as u32) * kinds.len())
        .sum::<usize>();
    let _ = writeln!(out, "pub const SIGNATURES: usize = {count};");
    let _ = writeln!(out, "pub const MAX_ARGS: usize = {MAX_ARGS};");
    out.push_str(
        r#"
/// Call `func_ptr` as the signature described by the argument and return kinds.
///
/// The three value slices each have one entry per argument. Integer kinds use
/// `ints`, kind 1 uses `f32s`, and kind 2 uses `f64s`. Float results return
/// as f64 bits.
///
/// # Safety
///
/// `func_ptr` must be a function of exactly the described signature.
pub unsafe fn dispatch(
    func_ptr: *mut std::ffi::c_void,
    ints: &[i64],
    f32s: &[f32],
    f64s: &[f64],
    arg_kinds: &[u8],
    ret_kind: u8,
) -> Option<i64> {
    let len = arg_kinds.len();
    if len > MAX_ARGS || ints.len() < len || f32s.len() < len || f64s.len() < len {
        return None;
    }
    let mut words = [0u64; MAX_ARGS];
    for (i, &kind) in arg_kinds.iter().enumerate() {
        words[i] = match kind {
            0 => ints[i] as u64,
            1 => f32s[i].to_bits() as u64,
            2 => f64s[i].to_bits(),
            _ => return None,
        };
    }
    unsafe { dispatch_by_pattern(func_ptr, &words[..len], ret_kind, pattern_of(arg_kinds)) }
}

/// The pattern formed from the argument kinds, least significant digit first.
pub fn pattern_of(arg_kinds: &[u8]) -> u32 {
    let mut pattern = 0u32;
    for &kind in arg_kinds.iter().rev() {
        pattern = pattern * 3 + kind as u32;
    }
    pattern
}

/// Call `func_ptr` with one word per argument and an already-folded kind pattern.
///
/// Each word holds an integer or pointer, the low 32 bits of an f32, or the
/// bits of an f64. Returns None for a signature outside the generated range.
///
/// # Safety
///
/// `func_ptr` must be a function of exactly the signature named by `pattern`
/// and `ret_kind`.
pub unsafe fn dispatch_by_pattern(
    func_ptr: *mut std::ffi::c_void,
    words: &[u64],
    ret_kind: u8,
    pattern: u32,
) -> Option<i64> {
    match (words.len(), ret_kind) {
"#,
    );
    for arity in 0..=MAX_ARGS {
        let pattern_count = 3usize.pow(arity as u32);
        let chunks = pattern_count.div_ceil(CHUNK_SIZE);
        for ret in 0..kinds.len() {
            let _ = writeln!(
                out,
                "        ({arity}, {ret}) => match pattern as usize / {CHUNK_SIZE} {{"
            );
            for chunk in 0..chunks {
                let _ = writeln!(
                    out,
                    "            {chunk} => unsafe {{ dispatch_{arity}_{ret}_{chunk}(func_ptr, words, pattern) }},"
                );
            }
            out.push_str("            _ => None,\n        },\n");
        }
    }
    out.push_str("        _ => None,\n    }\n}\n");

    for arity in 0..=MAX_ARGS {
        let pattern_count = 3usize.pow(arity as u32);
        for (ret_code, ret) in kinds.iter().enumerate() {
            for chunk in 0..pattern_count.div_ceil(CHUNK_SIZE) {
                let _ = writeln!(
                    out,
                    "\n#[inline(never)]\nunsafe fn dispatch_{arity}_{ret_code}_{chunk}(\n    func_ptr: *mut std::ffi::c_void,\n    _words: &[u64],\n    pattern: u32,\n) -> Option<i64> {{\n    Some(match pattern {{"
                );
                let start = chunk * CHUNK_SIZE;
                let end = (start + CHUNK_SIZE).min(pattern_count);
                for pattern in start..end {
                    let mut code = pattern;
                    let args = (0..arity)
                        .map(|_| {
                            let kind = kinds[code % kinds.len()];
                            code /= kinds.len();
                            kind
                        })
                        .collect::<Vec<_>>();
                    let params = args
                        .iter()
                        .map(|kind| kind.rust())
                        .collect::<Vec<_>>()
                        .join(", ");
                    let values = args
                        .iter()
                        .enumerate()
                        .map(|(i, kind)| match kind {
                            Kind::Int => format!("_words[{i}] as i64"),
                            Kind::F32 => format!("f32::from_bits(_words[{i}] as u32)"),
                            Kind::F64 => format!("f64::from_bits(_words[{i}])"),
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    let call = match ret {
                        Kind::Int => format!("f({values})"),
                        Kind::F32 => format!("(f({values}) as f64).to_bits() as i64"),
                        Kind::F64 => format!("f({values}).to_bits() as i64"),
                    };
                    let _ = writeln!(
                        out,
                        "        {pattern} => unsafe {{\n            let f: unsafe extern \"C\" fn({params}) -> {} = std::mem::transmute(func_ptr);\n            {call}\n        }},",
                        ret.rust()
                    );
                }
                out.push_str("        _ => return None,\n    })\n}\n");
            }
        }
    }

    let path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("dispatch.rs");
    fs::write(path, out).expect("writing the dispatch table");
}
