#![allow(warnings)]
// #![feature(new_zeroed_alloc)]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

pub mod air_pipeline;
pub mod bytecode;
pub mod bytecode_encode;
pub mod c_types;
pub mod callsite_profile;
pub mod cranelift;
pub mod intrinsics;
pub mod progress;
pub mod hl_bindings {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    // Generated by bindgen; its idioms are not ours to lint. The runtime-symbol
    // lint fires on its c_ulong-vs-usize libc declarations, which are what
    // bindgen emits for the platform headers.
    #![allow(
        unknown_lints,
        unnecessary_transmutes,
        suspicious_runtime_symbol_definitions
    )]
    #![allow(clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/hl_bindings.rs"));
}
pub mod jit_map;
pub mod layout;
pub mod llvm;
pub mod native_lib;
pub mod opcodes;
pub mod osr;
pub mod profile;
pub mod reachable;
pub mod reload;
pub mod target_abi;
pub mod types;

use hl_bindings as hl;

#[cfg(test)]
mod test_macro;
