use std::fmt::Write as _;
use std::{env, fs, path::PathBuf};

fn main() {
    cc::Build::new()
        .file("src/trap_boundary.c")
        .warnings(true)
        .compile("ash_interp_trap_boundary");

    println!("cargo:rerun-if-changed=src/trap_boundary.c");
    println!("cargo:rerun-if-changed=build.rs");
    write_float_dispatch();
}

/// The most arguments a generated signature covers.
///
/// Both calling conventions we target pass this many in registers, and no
/// primitive in the tree comes close.
const MAX_ARGS: u32 = 8;

/// Emit a call for every signature of up to [`MAX_ARGS`] arguments whose
/// floats are all `f64`.
///
/// A native is called by transmuting its address to a function pointer, which
/// means the signature has to exist in the source. The hand-written table in
/// `natives.rs` grew an arm each time a library used a combination nobody had
/// used before -- three in one afternoon, once a graphics library started
/// passing colours around -- and every gap was a clean runtime error rather
/// than a wrong answer, but a wall all the same.
///
/// There are 511 argument patterns up to eight arguments and two ways to
/// return, so all of them is 1022 arms: more than anyone would write and
/// nothing a machine minds.
///
/// `f32` is deliberately not covered. It is passed differently from `f64`, so
/// including it would mean three states per argument rather than two and tens
/// of thousands of arms; the handful of `f32` primitives keep their
/// hand-written entries.
fn write_float_dispatch() {
    let mut out = String::from(
        "// GENERATED by build.rs. Edit the generator, not this file.\n\n\
         /// Every signature of up to eight arguments whose floats are `f64`.\n\
         ///\n\
         /// `None` if the signature is longer than that. `ints` and `floats`\n\
         /// are both as long as the argument list; `float_mask` says which of\n\
         /// the two to read for each position.\n\
         ///\n\
         /// # Safety\n\
         /// `func_ptr` must be a function of exactly the signature the mask\n\
         /// and `ret_is_float` describe.\n\
         pub(crate) unsafe fn dispatch_all_f64(\n\
         \x20   func_ptr: *mut std::ffi::c_void,\n\
         \x20   ints: &[i64],\n\
         \x20   floats: &[f64],\n\
         \x20   ret_is_float: bool,\n\
         \x20   float_mask: u32,\n\
         ) -> Option<i64> {\n\
         \x20   Some(match (ints.len(), ret_is_float, float_mask) {\n",
    );

    for arity in 0..=MAX_ARGS {
        for mask in 0..(1u32 << arity) {
            for ret_is_float in [false, true] {
                let params = (0..arity)
                    .map(|i| if mask >> i & 1 == 1 { "f64" } else { "i64" })
                    .collect::<Vec<_>>()
                    .join(", ");
                let args = (0..arity)
                    .map(|i| {
                        if mask >> i & 1 == 1 {
                            format!("floats[{i}]")
                        } else {
                            format!("ints[{i}]")
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                let (ret, call) = if ret_is_float {
                    ("f64", format!("f({args}).to_bits() as i64"))
                } else {
                    ("i64", format!("f({args})"))
                };
                let _ = write!(
                    out,
                    "        ({arity}, {ret_is_float}, {mask}) => {{\n\
                     \x20           let f: unsafe extern \"C\" fn({params}) -> {ret} =\n\
                     \x20               std::mem::transmute(func_ptr);\n\
                     \x20           {call}\n\
                     \x20       }}\n"
                );
            }
        }
    }
    out.push_str("        _ => return None,\n    })\n}\n");

    let path = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("float_dispatch.rs");
    fs::write(path, out).expect("writing the float dispatch table");
}
