//! The page that runs an ash wasm module in a browser.
//!
//! `index.html` starts `worker.js`, which runs the program; the page starts
//! the `thread.js` agents Haxe threads run on and, for a program that draws,
//! `display.js`. The browser host (`ash_browser.js`, `ash_browser_bg.wasm`) is
//! built into this crate by its build script, so the page needs nothing from
//! the machine it is written on.
//!
//! [`write_page`] puts the files beside a module; [`files`] hands them over for
//! a server that keeps them in memory.

use std::borrow::Cow;
use std::io;
use std::path::Path;

const INDEX_HTML: &str = include_str!("../page/index.html");
const WORKER_JS: &str = include_str!("../page/worker.js");
const THREAD_JS: &str = include_str!("../page/thread.js");
const DISPLAY_JS: &str = include_str!("../page/display.js");
const HOST_JS: &str = include_str!(concat!(env!("OUT_DIR"), "/host/ash_browser.js"));
const HOST_WASM: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/host/ash_browser_bg.wasm"));

/// Marks an `index.html` ash wrote, which [`write_page`] may rewrite.
const GENERATED: &str = "<!-- generated by ash;";

/// The page's index for the module file `module_name` (`main.wasm`, not a
/// path): the module's name is written into both its title and its script.
pub fn index_html(module_name: &str) -> String {
    let text = module_name
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;");
    let mut json = String::from("\"");
    for c in module_name.chars() {
        match c {
            '"' => json.push_str("\\\""),
            '\\' => json.push_str("\\\\"),
            // `</script>` inside the string would end the script element.
            '<' => json.push_str("\\u003c"),
            c if (c as u32) < 0x20 => json.push_str(&format!("\\u{:04x}", c as u32)),
            c => json.push(c),
        }
    }
    json.push('"');
    INDEX_HTML
        .replace("__ASH_MODULE_TEXT__", &text)
        .replace("__ASH_MODULE_JSON__", &json)
}

/// Every file of the page for the module file `module_name`, by the name it
/// goes under beside the module.
pub fn files(module_name: &str) -> Vec<(&'static str, Cow<'static, [u8]>)> {
    vec![
        (
            "index.html",
            Cow::Owned(index_html(module_name).into_bytes()),
        ),
        ("worker.js", Cow::Borrowed(WORKER_JS.as_bytes())),
        ("thread.js", Cow::Borrowed(THREAD_JS.as_bytes())),
        ("display.js", Cow::Borrowed(DISPLAY_JS.as_bytes())),
        ("ash_browser.js", Cow::Borrowed(HOST_JS.as_bytes())),
        ("ash_browser_bg.wasm", Cow::Borrowed(HOST_WASM)),
    ]
}

/// What [`write_page`] did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Written {
    /// An `index.html` without ash's first-line marker was already there and
    /// was left alone.
    pub index_kept: bool,
}

/// Write the page for `module` beside it.
///
/// An `index.html` the user wrote is kept; one ash wrote is rewritten so it
/// names this module.
pub fn write_page(module: &Path) -> io::Result<Written> {
    let name = module
        .file_name()
        .and_then(|n| n.to_str())
        .ok_or_else(|| io::Error::other(format!("{} has no file name", module.display())))?;
    let dir = module
        .parent()
        .filter(|d| !d.as_os_str().is_empty())
        .unwrap_or(Path::new("."));
    let index = dir.join("index.html");
    let index_kept = match std::fs::read_to_string(&index) {
        Ok(existing) => !existing.contains(GENERATED),
        Err(_) => false,
    };
    for (file, contents) in files(name) {
        if file == "index.html" && index_kept {
            continue;
        }
        std::fs::write(dir.join(file), contents)?;
    }
    Ok(Written { index_kept })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_module_name_is_escaped_for_the_title_and_the_script() {
        let page = index_html("a\"</script><b>.wasm");
        assert!(page.contains("<title>a\"&lt;/script&gt;&lt;b&gt;.wasm</title>"));
        assert!(page.contains("\"./\" + \"a\\\"\\u003c/script>\\u003cb>.wasm\""));
        assert!(!page.contains("__ASH_MODULE"));
    }

    #[test]
    fn a_page_the_user_wrote_is_kept_and_one_ash_wrote_is_rewritten() {
        let dir = std::env::temp_dir().join(format!("ash-page-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let module = dir.join("app.wasm");

        let first = write_page(&module).unwrap();
        assert!(!first.index_kept);
        for (file, _) in files("app.wasm") {
            assert!(dir.join(file).is_file(), "{file} was not written");
        }
        let written = std::fs::read_to_string(dir.join("index.html")).unwrap();
        assert!(written.contains("\"app.wasm\""));

        std::fs::write(dir.join("index.html"), "mine").unwrap();
        assert!(write_page(&module).unwrap().index_kept);
        assert_eq!(
            std::fs::read_to_string(dir.join("index.html")).unwrap(),
            "mine"
        );

        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn the_host_is_built_in() {
        assert!(HOST_JS.contains("run_thread"));
        // `init()` with no argument has to find the module beside the script.
        assert!(HOST_JS.contains("new URL('ash_browser_bg.wasm', import.meta.url)"));
        assert_eq!(&HOST_WASM[..4], b"\0asm");
    }
}
