//! The page that runs an ash wasm module in a browser.
//!
//! `index.html` starts `worker.js`, which runs the program; the page starts
//! the `thread.js` agents Haxe threads run on and, for a program that draws,
//! `display.js`. The browser host (`ash_browser.js`, `ash_browser_bg.wasm`) is
//! built into this crate by its build script, so the page needs nothing from
//! the machine it is written on.
//!
//! [`write_page`] puts the files beside a module; [`files`] hands them over for
//! a server that keeps them in memory. `write_page` also lists the native
//! libraries beside the module, wasm side modules, in `libraries.json`, which
//! `worker.js` fetches with the program.

use std::borrow::Cow;
use std::io;
use std::path::Path;

const INDEX_HTML: &str = include_str!("../page/index.html");
const WORKER_JS: &str = include_str!("../page/worker.js");
const THREAD_JS: &str = include_str!("../page/thread.js");
const DISPLAY_JS: &str = include_str!("../page/display.js");
/// The window's page side; a program reaches it with
/// `ash_host_agent("window", block)`. See docs/wasm/window.md.
const WINDOW_MJS: &str = include_str!("../page/window.mjs");
const HOST_JS: &str = include_str!(concat!(env!("OUT_DIR"), "/host/ash_browser.js"));
const HOST_WASM: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/host/ash_browser_bg.wasm"));

/// Marks an `index.html` ash wrote, which [`write_page`] may rewrite.
const GENERATED: &str = "<!-- generated by ash;";

/// The page's index for the module file `module_name` (`main.wasm`, not a
/// path): the module's name is written into both its title and its script.
pub fn index_html(module_name: &str) -> String {
    let text = module_name
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;");
    let mut json = String::from("\"");
    for c in module_name.chars() {
        match c {
            '"' => json.push_str("\\\""),
            '\\' => json.push_str("\\\\"),
            // `</script>` inside the string would end the script element.
            '<' => json.push_str("\\u003c"),
            c if (c as u32) < 0x20 => json.push_str(&format!("\\u{:04x}", c as u32)),
            c => json.push(c),
        }
    }
    json.push('"');
    INDEX_HTML
        .replace("__ASH_MODULE_TEXT__", &text)
        .replace("__ASH_MODULE_JSON__", &json)
}

/// Every file of the page for the module file `module_name`, by the name it
/// goes under beside the module.
pub fn files(module_name: &str) -> Vec<(&'static str, Cow<'static, [u8]>)> {
    vec![
        (
            "index.html",
            Cow::Owned(index_html(module_name).into_bytes()),
        ),
        ("worker.js", Cow::Borrowed(WORKER_JS.as_bytes())),
        ("thread.js", Cow::Borrowed(THREAD_JS.as_bytes())),
        ("display.js", Cow::Borrowed(DISPLAY_JS.as_bytes())),
        ("window.mjs", Cow::Borrowed(WINDOW_MJS.as_bytes())),
        ("ash_browser.js", Cow::Borrowed(HOST_JS.as_bytes())),
        ("ash_browser_bg.wasm", Cow::Borrowed(HOST_WASM)),
    ]
}

/// What [`write_page`] did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Written {
    /// An `index.html` without ash's first-line marker was already there and
    /// was left alone.
    pub index_kept: bool,
}

/// Whether `bytes` begin a wasm side module: a module whose first section is
/// the custom section `dylink.0`.
pub fn is_side_module(bytes: &[u8]) -> bool {
    const HEADER: &[u8] = b"\0asm\x01\0\0\0";
    let Some(rest) = bytes.strip_prefix(HEADER) else {
        return false;
    };
    let mut at = 0usize;
    let leb = |at: &mut usize| -> Option<u32> {
        let mut value = 0u32;
        for shift in (0..35).step_by(7) {
            let byte = *rest.get(*at)?;
            *at += 1;
            value |= u32::from(byte & 0x7f) << shift;
            if byte & 0x80 == 0 {
                return Some(value);
            }
        }
        None
    };
    if rest.first() != Some(&0) {
        return false;
    }
    at += 1;
    if leb(&mut at).is_none() {
        return false;
    }
    let Some(len) = leb(&mut at) else {
        return false;
    };
    rest.get(at..at + len as usize) == Some(b"dylink.0".as_slice())
}

/// The native libraries beside `module`: the stem of every other `.wasm`
/// file there that is a side module, sorted.
pub fn libraries_beside(module: &Path) -> Vec<String> {
    use std::io::Read;
    let dir = module
        .parent()
        .filter(|d| !d.as_os_str().is_empty())
        .unwrap_or(Path::new("."));
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut names: Vec<String> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.file_name() != module.file_name() && p.extension().is_some_and(|e| e == "wasm")
        })
        .filter(|p| {
            let mut head = [0u8; 32];
            std::fs::File::open(p)
                .and_then(|mut f| f.read(&mut head))
                .is_ok_and(|n| is_side_module(&head[..n]))
        })
        .filter_map(|p| p.file_stem()?.to_str().map(str::to_string))
        .collect();
    names.sort();
    names
}

/// `names` as the JSON array `libraries.json` holds.
fn libraries_json(names: &[String]) -> String {
    let quoted: Vec<String> = names
        .iter()
        .map(|n| format!("\"{}\"", n.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect();
    format!("[{}]\n", quoted.join(", "))
}

/// Write the page for `module` beside it.
///
/// An `index.html` the user wrote is kept; one ash wrote is rewritten so it
/// names this module. `libraries.json` is always rewritten.
pub fn write_page(module: &Path) -> io::Result<Written> {
    let name = module
        .file_name()
        .and_then(|n| n.to_str())
        .ok_or_else(|| io::Error::other(format!("{} has no file name", module.display())))?;
    let dir = module
        .parent()
        .filter(|d| !d.as_os_str().is_empty())
        .unwrap_or(Path::new("."));
    let index = dir.join("index.html");
    let index_kept = match std::fs::read_to_string(&index) {
        Ok(existing) => !existing.contains(GENERATED),
        Err(_) => false,
    };
    for (file, contents) in files(name) {
        if file == "index.html" && index_kept {
            continue;
        }
        std::fs::write(dir.join(file), contents)?;
    }
    std::fs::write(
        dir.join("libraries.json"),
        libraries_json(&libraries_beside(module)),
    )?;
    Ok(Written { index_kept })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_module_name_is_escaped_for_the_title_and_the_script() {
        let page = index_html("a\"</script><b>.wasm");
        assert!(page.contains("<title>a\"&lt;/script&gt;&lt;b&gt;.wasm</title>"));
        assert!(page.contains("\"./\" + \"a\\\"\\u003c/script>\\u003cb>.wasm\""));
        assert!(!page.contains("__ASH_MODULE"));
    }

    #[test]
    fn a_side_module_is_known_by_its_first_section() {
        let mut side = b"\0asm\x01\0\0\0\0\x0f\x08dylink.0".to_vec();
        side.extend([0u8; 6]);
        assert!(is_side_module(&side));
        let program = b"\0asm\x01\0\0\0\x01\x04\x01\x60\0\0";
        assert!(!is_side_module(program));
        assert!(!is_side_module(b"\0asm"));
    }

    #[test]
    fn the_libraries_beside_a_module_are_listed() {
        let dir = std::env::temp_dir().join(format!("ash-page-libs-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("xwindow.wasm"), b"\0asm\x01\0\0\0\0\x0f\x08dylink.0").unwrap();
        std::fs::write(dir.join("other.wasm"), b"\0asm\x01\0\0\0\x01\x01\0").unwrap();
        let module = dir.join("app.wasm");
        std::fs::write(&module, b"\0asm\x01\0\0\0").unwrap();
        write_page(&module).unwrap();
        let listed = std::fs::read_to_string(dir.join("libraries.json")).unwrap();
        let _ = std::fs::remove_dir_all(&dir);
        assert_eq!(listed, "[\"xwindow\"]\n");
    }

    #[test]
    fn a_page_the_user_wrote_is_kept_and_one_ash_wrote_is_rewritten() {
        let dir = std::env::temp_dir().join(format!("ash-page-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let module = dir.join("app.wasm");

        let first = write_page(&module).unwrap();
        assert!(!first.index_kept);
        for (file, _) in files("app.wasm") {
            assert!(dir.join(file).is_file(), "{file} was not written");
        }
        let written = std::fs::read_to_string(dir.join("index.html")).unwrap();
        assert!(written.contains("\"app.wasm\""));

        std::fs::write(dir.join("index.html"), "mine").unwrap();
        assert!(write_page(&module).unwrap().index_kept);
        assert_eq!(
            std::fs::read_to_string(dir.join("index.html")).unwrap(),
            "mine"
        );

        std::fs::remove_dir_all(&dir).unwrap();
    }

    #[test]
    fn the_host_is_built_in() {
        assert!(HOST_JS.contains("run_thread"));
        // `init()` with no argument has to find the module beside the script.
        assert!(HOST_JS.contains("new URL('ash_browser_bg.wasm', import.meta.url)"));
        assert_eq!(&HOST_WASM[..4], b"\0asm");
    }
}
