//! The `sdl` library for wasm: every primitive the Heaps base3d example
//! reaches, forwarding to the host.
//!
//! GENERATED by `scripts/generate_sdl_shim.py` from the signatures `sdl.hdll`
//! reports for itself. Edit the generator, not this file.
//!
//! Nothing here decides anything. A window, a GL context and a frame belong
//! to whoever is embedding the program -- a canvas in a page, or a recorder
//! under a headless host -- so every function is the same shape: unwrap what
//! HashLink boxed, hand the plain values to the host, box whatever comes
//! back.

use std::ffi::c_void;

// Not every library needs all of it: `ui` boxes nothing.
#[allow(unused_imports)]
use hl_abi::*;


#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_cursor_create(a0: i32, a1: i32, a2: i32) -> i32;
}

/// `PXsdl_surface_ii_Xsdl_cursor_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_cursor_create(a0: *mut c_void, a1: i32, a2: i32) -> *mut c_void {
    ash_host_sdl_cursor_create(a0 as i32, a1, a2) as *mut c_void
}
define_prim!(hlp_cursor_create, sdl_cursor_create, "PXsdl_surface_ii_Xsdl_cursor_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_cursor_create_system(a0: i32) -> i32;
}

/// `Pi_Xsdl_cursor_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_cursor_create_system(a0: i32) -> *mut c_void {
    ash_host_sdl_cursor_create_system(a0) as *mut c_void
}
define_prim!(hlp_cursor_create_system, sdl_cursor_create_system, "Pi_Xsdl_cursor_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_delay(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_delay(a0: i32) {
    ash_host_sdl_delay(a0);
}
define_prim!(hlp_delay, sdl_delay, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_detect_keyboard_layout() -> i32;
}

/// `P_B`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_detect_keyboard_layout() -> *mut vbyte {
    ash_host_sdl_detect_keyboard_layout() as *mut vbyte
}
define_prim!(hlp_detect_keyboard_layout, sdl_detect_keyboard_layout, "P_B");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_detect_win32() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_detect_win32() -> bool {
    ash_host_sdl_detect_win32() != 0
}
define_prim!(hlp_detect_win32, sdl_detect_win32, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_event_loop(a0: i32) -> i32;
}

/// `PD_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_event_loop(a0: *mut vdynamic) -> bool {
    ash_host_sdl_event_loop(a0 as i32) != 0
}
define_prim!(hlp_event_loop, sdl_event_loop, "PD_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_free_cursor(a0: i32);
}

/// `PXsdl_cursor__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_free_cursor(a0: *mut c_void) {
    ash_host_sdl_free_cursor(a0 as i32);
}
define_prim!(hlp_free_cursor, sdl_free_cursor, "PXsdl_cursor__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_free_surface(a0: i32);
}

/// `PXsdl_surface__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_free_surface(a0: *mut c_void) {
    ash_host_sdl_free_surface(a0 as i32);
}
define_prim!(hlp_free_surface, sdl_free_surface, "PXsdl_surface__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gctrl_close(a0: i32);
}

/// `PXsdl_gamecontroller__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gctrl_close(a0: *mut c_void) {
    ash_host_sdl_gctrl_close(a0 as i32);
}
define_prim!(hlp_gctrl_close, sdl_gctrl_close, "PXsdl_gamecontroller__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gctrl_count() -> i32;
}

/// `P_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gctrl_count() -> i32 {
    ash_host_sdl_gctrl_count()
}
define_prim!(hlp_gctrl_count, sdl_gctrl_count, "P_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gctrl_get_axis(a0: i32, a1: i32) -> i32;
}

/// `PXsdl_gamecontroller_i_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gctrl_get_axis(a0: *mut c_void, a1: i32) -> i32 {
    ash_host_sdl_gctrl_get_axis(a0 as i32, a1)
}
define_prim!(hlp_gctrl_get_axis, sdl_gctrl_get_axis, "PXsdl_gamecontroller_i_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gctrl_get_button(a0: i32, a1: i32) -> i32;
}

/// `PXsdl_gamecontroller_i_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gctrl_get_button(a0: *mut c_void, a1: i32) -> bool {
    ash_host_sdl_gctrl_get_button(a0 as i32, a1) != 0
}
define_prim!(hlp_gctrl_get_button, sdl_gctrl_get_button, "PXsdl_gamecontroller_i_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gctrl_get_id(a0: i32) -> i32;
}

/// `PXsdl_gamecontroller__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gctrl_get_id(a0: *mut c_void) -> i32 {
    ash_host_sdl_gctrl_get_id(a0 as i32)
}
define_prim!(hlp_gctrl_get_id, sdl_gctrl_get_id, "PXsdl_gamecontroller__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gctrl_get_name(a0: i32) -> i32;
}

/// `PXsdl_gamecontroller__B`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gctrl_get_name(a0: *mut c_void) -> *mut vbyte {
    ash_host_sdl_gctrl_get_name(a0 as i32) as *mut vbyte
}
define_prim!(hlp_gctrl_get_name, sdl_gctrl_get_name, "PXsdl_gamecontroller__B");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gctrl_open(a0: i32) -> i32;
}

/// `Pi_Xsdl_gamecontroller_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gctrl_open(a0: i32) -> *mut c_void {
    ash_host_sdl_gctrl_open(a0) as *mut c_void
}
define_prim!(hlp_gctrl_open, sdl_gctrl_open, "Pi_Xsdl_gamecontroller_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_clipboard_text() -> i32;
}

/// `P_B`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_clipboard_text() -> *mut vbyte {
    ash_host_sdl_get_clipboard_text() as *mut vbyte
}
define_prim!(hlp_get_clipboard_text, sdl_get_clipboard_text, "P_B");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_current_display_mode(a0: i32, a1: i32) -> i32;
}

/// `Pib_D`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_current_display_mode(a0: i32, a1: bool) -> *mut vdynamic {
    box_i32(ash_host_sdl_get_current_display_mode(a0, a1 as i32))
}
define_prim!(hlp_get_current_display_mode, sdl_get_current_display_mode, "Pib_D");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_devices() -> i32;
}

/// `P_A`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_devices() -> *mut varray {
    { let _ = ash_host_sdl_get_devices(); empty_array() }
}
define_prim!(hlp_get_devices, sdl_get_devices, "P_A");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_display_modes(a0: i32) -> i32;
}

/// `Pi_A`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_display_modes(a0: i32) -> *mut varray {
    { let _ = ash_host_sdl_get_display_modes(a0); empty_array() }
}
define_prim!(hlp_get_display_modes, sdl_get_display_modes, "Pi_A");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_displays() -> i32;
}

/// `P_A`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_displays() -> *mut varray {
    { let _ = ash_host_sdl_get_displays(); empty_array() }
}
define_prim!(hlp_get_displays, sdl_get_displays, "P_A");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_drag_and_drop_enabled() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_drag_and_drop_enabled() -> bool {
    ash_host_sdl_get_drag_and_drop_enabled() != 0
}
define_prim!(hlp_get_drag_and_drop_enabled, sdl_get_drag_and_drop_enabled, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_framerate(a0: i32) -> i32;
}

/// `PXsdl_window__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_framerate(a0: *mut c_void) -> i32 {
    ash_host_sdl_get_framerate(a0 as i32)
}
define_prim!(hlp_get_framerate, sdl_get_framerate, "PXsdl_window__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_global_mouse_state(a0: i32, a1: i32) -> i32;
}

/// `PRiRi_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_global_mouse_state(a0: *mut i32, a1: *mut i32) -> i32 {
    ash_host_sdl_get_global_mouse_state(a0 as i32, a1 as i32)
}
define_prim!(hlp_get_global_mouse_state, sdl_get_global_mouse_state, "PRiRi_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_relative_mouse_mode() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_relative_mouse_mode() -> bool {
    ash_host_sdl_get_relative_mouse_mode() != 0
}
define_prim!(hlp_get_relative_mouse_mode, sdl_get_relative_mouse_mode, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_screen_height() -> i32;
}

/// `P_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_screen_height() -> i32 {
    ash_host_sdl_get_screen_height()
}
define_prim!(hlp_get_screen_height, sdl_get_screen_height, "P_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_screen_height_of_window(a0: i32) -> i32;
}

/// `PXsdl_window__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_screen_height_of_window(a0: *mut c_void) -> i32 {
    ash_host_sdl_get_screen_height_of_window(a0 as i32)
}
define_prim!(hlp_get_screen_height_of_window, sdl_get_screen_height_of_window, "PXsdl_window__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_screen_width() -> i32;
}

/// `P_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_screen_width() -> i32 {
    ash_host_sdl_get_screen_width()
}
define_prim!(hlp_get_screen_width, sdl_get_screen_width, "P_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_screen_width_of_window(a0: i32) -> i32;
}

/// `PXsdl_window__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_screen_width_of_window(a0: *mut c_void) -> i32 {
    ash_host_sdl_get_screen_width_of_window(a0 as i32)
}
define_prim!(hlp_get_screen_width_of_window, sdl_get_screen_width_of_window, "PXsdl_window__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_get_window_grab(a0: i32) -> i32;
}

/// `PXsdl_window__b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_get_window_grab(a0: *mut c_void) -> bool {
    ash_host_sdl_get_window_grab(a0 as i32) != 0
}
define_prim!(hlp_get_window_grab, sdl_get_window_grab, "PXsdl_window__b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_active_texture(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_active_texture(a0: i32) {
    ash_host_sdl_gl_active_texture(a0);
}
define_prim!(hlp_gl_active_texture, sdl_gl_active_texture, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_attach_shader(a0: i32, a1: i32);
}

/// `PNiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_attach_shader(a0: *mut vdynamic, a1: *mut vdynamic) {
    ash_host_sdl_gl_attach_shader(unbox_i32(a0), unbox_i32(a1));
}
define_prim!(hlp_gl_attach_shader, sdl_gl_attach_shader, "PNiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_begin_query(a0: i32, a1: i32);
}

/// `PiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_begin_query(a0: i32, a1: *mut vdynamic) {
    ash_host_sdl_gl_begin_query(a0, unbox_i32(a1));
}
define_prim!(hlp_gl_begin_query, sdl_gl_begin_query, "PiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_buffer(a0: i32, a1: i32);
}

/// `PiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_buffer(a0: i32, a1: *mut vdynamic) {
    ash_host_sdl_gl_bind_buffer(a0, unbox_i32(a1));
}
define_prim!(hlp_gl_bind_buffer, sdl_gl_bind_buffer, "PiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_buffer_base(a0: i32, a1: i32, a2: i32);
}

/// `PiiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_buffer_base(a0: i32, a1: i32, a2: *mut vdynamic) {
    ash_host_sdl_gl_bind_buffer_base(a0, a1, unbox_i32(a2));
}
define_prim!(hlp_gl_bind_buffer_base, sdl_gl_bind_buffer_base, "PiiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_frag_data_location(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `PNiiOBi__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_frag_data_location(a0: *mut vdynamic, a1: i32, a2: *mut vstring) {
    ash_host_sdl_gl_bind_frag_data_location(unbox_i32(a0), a1, string_bytes(a2), string_length(a2));
}
define_prim!(hlp_gl_bind_frag_data_location, sdl_gl_bind_frag_data_location, "PNiiOBi__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_framebuffer(a0: i32, a1: i32);
}

/// `PiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_framebuffer(a0: i32, a1: *mut vdynamic) {
    ash_host_sdl_gl_bind_framebuffer(a0, unbox_i32(a1));
}
define_prim!(hlp_gl_bind_framebuffer, sdl_gl_bind_framebuffer, "PiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_image_texture(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32);
}

/// `Piiibiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_image_texture(a0: i32, a1: i32, a2: i32, a3: bool, a4: i32, a5: i32, a6: i32) {
    ash_host_sdl_gl_bind_image_texture(a0, a1, a2, a3 as i32, a4, a5, a6);
}
define_prim!(hlp_gl_bind_image_texture, sdl_gl_bind_image_texture, "Piiibiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_renderbuffer(a0: i32, a1: i32);
}

/// `PiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_renderbuffer(a0: i32, a1: *mut vdynamic) {
    ash_host_sdl_gl_bind_renderbuffer(a0, unbox_i32(a1));
}
define_prim!(hlp_gl_bind_renderbuffer, sdl_gl_bind_renderbuffer, "PiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_texture(a0: i32, a1: i32);
}

/// `PiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_texture(a0: i32, a1: *mut vdynamic) {
    ash_host_sdl_gl_bind_texture(a0, unbox_i32(a1));
}
define_prim!(hlp_gl_bind_texture, sdl_gl_bind_texture, "PiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_vertex_array(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_vertex_array(a0: *mut vdynamic) {
    ash_host_sdl_gl_bind_vertex_array(unbox_i32(a0));
}
define_prim!(hlp_gl_bind_vertex_array, sdl_gl_bind_vertex_array, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_blend_equation(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_blend_equation(a0: i32) {
    ash_host_sdl_gl_blend_equation(a0);
}
define_prim!(hlp_gl_blend_equation, sdl_gl_blend_equation, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_blend_equation_separate(a0: i32, a1: i32);
}

/// `Pii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_blend_equation_separate(a0: i32, a1: i32) {
    ash_host_sdl_gl_blend_equation_separate(a0, a1);
}
define_prim!(hlp_gl_blend_equation_separate, sdl_gl_blend_equation_separate, "Pii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_blend_func(a0: i32, a1: i32);
}

/// `Pii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_blend_func(a0: i32, a1: i32) {
    ash_host_sdl_gl_blend_func(a0, a1);
}
define_prim!(hlp_gl_blend_func, sdl_gl_blend_func, "Pii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_blend_func_separate(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_blend_func_separate(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_blend_func_separate(a0, a1, a2, a3);
}
define_prim!(hlp_gl_blend_func_separate, sdl_gl_blend_func_separate, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_blit_framebuffer(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32);
}

/// `Piiiiiiiiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_blit_framebuffer(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32) {
    ash_host_sdl_gl_blit_framebuffer(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
}
define_prim!(hlp_gl_blit_framebuffer, sdl_gl_blit_framebuffer, "Piiiiiiiiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_buffer_data(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `PiiBi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_buffer_data(a0: i32, a1: i32, a2: *mut vbyte, a3: i32) {
    ash_host_sdl_gl_buffer_data(a0, a1, a2 as i32, a3);
}
define_prim!(hlp_gl_buffer_data, sdl_gl_buffer_data, "PiiBi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_buffer_data_size(a0: i32, a1: i32, a2: i32);
}

/// `Piii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_buffer_data_size(a0: i32, a1: i32, a2: i32) {
    ash_host_sdl_gl_buffer_data_size(a0, a1, a2);
}
define_prim!(hlp_gl_buffer_data_size, sdl_gl_buffer_data_size, "Piii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_buffer_sub_data(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `PiiBii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_buffer_sub_data(a0: i32, a1: i32, a2: *mut vbyte, a3: i32, a4: i32) {
    ash_host_sdl_gl_buffer_sub_data(a0, a1, a2 as i32, a3, a4);
}
define_prim!(hlp_gl_buffer_sub_data, sdl_gl_buffer_sub_data, "PiiBii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_clear(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_clear(a0: i32) {
    ash_host_sdl_gl_clear(a0);
}
define_prim!(hlp_gl_clear, sdl_gl_clear, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_clear_color(a0: f64, a1: f64, a2: f64, a3: f64);
}

/// `Pdddd_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_clear_color(a0: f64, a1: f64, a2: f64, a3: f64) {
    ash_host_sdl_gl_clear_color(a0, a1, a2, a3);
}
define_prim!(hlp_gl_clear_color, sdl_gl_clear_color, "Pdddd_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_clear_depth(a0: f64);
}

/// `Pd_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_clear_depth(a0: f64) {
    ash_host_sdl_gl_clear_depth(a0);
}
define_prim!(hlp_gl_clear_depth, sdl_gl_clear_depth, "Pd_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_clear_stencil(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_clear_stencil(a0: i32) {
    ash_host_sdl_gl_clear_stencil(a0);
}
define_prim!(hlp_gl_clear_stencil, sdl_gl_clear_stencil, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_color_mask(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Pbbbb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_color_mask(a0: bool, a1: bool, a2: bool, a3: bool) {
    ash_host_sdl_gl_color_mask(a0 as i32, a1 as i32, a2 as i32, a3 as i32);
}
define_prim!(hlp_gl_color_mask, sdl_gl_color_mask, "Pbbbb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_color_maski(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `Pibbbb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_color_maski(a0: i32, a1: bool, a2: bool, a3: bool, a4: bool) {
    ash_host_sdl_gl_color_maski(a0, a1 as i32, a2 as i32, a3 as i32, a4 as i32);
}
define_prim!(hlp_gl_color_maski, sdl_gl_color_maski, "Pibbbb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_compile_shader(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_compile_shader(a0: *mut vdynamic) {
    ash_host_sdl_gl_compile_shader(unbox_i32(a0));
}
define_prim!(hlp_gl_compile_shader, sdl_gl_compile_shader, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_compressed_tex_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32);
}

/// `PiiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_compressed_tex_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: *mut vbyte) {
    ash_host_sdl_gl_compressed_tex_image2d(a0, a1, a2, a3, a4, a5, a6, a7 as i32);
}
define_prim!(hlp_gl_compressed_tex_image2d, sdl_gl_compressed_tex_image2d, "PiiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_compressed_tex_image3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32);
}

/// `PiiiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_compressed_tex_image3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: *mut vbyte) {
    ash_host_sdl_gl_compressed_tex_image3d(a0, a1, a2, a3, a4, a5, a6, a7, a8 as i32);
}
define_prim!(hlp_gl_compressed_tex_image3d, sdl_gl_compressed_tex_image3d, "PiiiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_compressed_tex_sub_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32);
}

/// `PiiiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_compressed_tex_sub_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: *mut vbyte) {
    ash_host_sdl_gl_compressed_tex_sub_image2d(a0, a1, a2, a3, a4, a5, a6, a7, a8 as i32);
}
define_prim!(hlp_gl_compressed_tex_sub_image2d, sdl_gl_compressed_tex_sub_image2d, "PiiiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_compressed_tex_sub_image3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32, a10: i32);
}

/// `PiiiiiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_compressed_tex_sub_image3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32, a10: *mut vbyte) {
    ash_host_sdl_gl_compressed_tex_sub_image3d(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10 as i32);
}
define_prim!(hlp_gl_compressed_tex_sub_image3d, sdl_gl_compressed_tex_sub_image3d, "PiiiiiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_buffer() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_buffer() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_buffer())
}
define_prim!(hlp_gl_create_buffer, sdl_gl_create_buffer, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_framebuffer() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_framebuffer() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_framebuffer())
}
define_prim!(hlp_gl_create_framebuffer, sdl_gl_create_framebuffer, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_program() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_program() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_program())
}
define_prim!(hlp_gl_create_program, sdl_gl_create_program, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_query() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_query() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_query())
}
define_prim!(hlp_gl_create_query, sdl_gl_create_query, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_renderbuffer() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_renderbuffer() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_renderbuffer())
}
define_prim!(hlp_gl_create_renderbuffer, sdl_gl_create_renderbuffer, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_shader(a0: i32) -> i32;
}

/// `Pi_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_shader(a0: i32) -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_shader(a0))
}
define_prim!(hlp_gl_create_shader, sdl_gl_create_shader, "Pi_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_texture() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_texture() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_texture())
}
define_prim!(hlp_gl_create_texture, sdl_gl_create_texture, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_vertex_array() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_vertex_array() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_vertex_array())
}
define_prim!(hlp_gl_create_vertex_array, sdl_gl_create_vertex_array, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_cull_face(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_cull_face(a0: i32) {
    ash_host_sdl_gl_cull_face(a0);
}
define_prim!(hlp_gl_cull_face, sdl_gl_cull_face, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_delete_buffer(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_delete_buffer(a0: *mut vdynamic) {
    ash_host_sdl_gl_delete_buffer(unbox_i32(a0));
}
define_prim!(hlp_gl_delete_buffer, sdl_gl_delete_buffer, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_delete_framebuffer(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_delete_framebuffer(a0: *mut vdynamic) {
    ash_host_sdl_gl_delete_framebuffer(unbox_i32(a0));
}
define_prim!(hlp_gl_delete_framebuffer, sdl_gl_delete_framebuffer, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_delete_query(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_delete_query(a0: *mut vdynamic) {
    ash_host_sdl_gl_delete_query(unbox_i32(a0));
}
define_prim!(hlp_gl_delete_query, sdl_gl_delete_query, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_delete_renderbuffer(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_delete_renderbuffer(a0: *mut vdynamic) {
    ash_host_sdl_gl_delete_renderbuffer(unbox_i32(a0));
}
define_prim!(hlp_gl_delete_renderbuffer, sdl_gl_delete_renderbuffer, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_delete_shader(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_delete_shader(a0: *mut vdynamic) {
    ash_host_sdl_gl_delete_shader(unbox_i32(a0));
}
define_prim!(hlp_gl_delete_shader, sdl_gl_delete_shader, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_delete_texture(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_delete_texture(a0: *mut vdynamic) {
    ash_host_sdl_gl_delete_texture(unbox_i32(a0));
}
define_prim!(hlp_gl_delete_texture, sdl_gl_delete_texture, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_delete_vertex_array(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_delete_vertex_array(a0: *mut vdynamic) {
    ash_host_sdl_gl_delete_vertex_array(unbox_i32(a0));
}
define_prim!(hlp_gl_delete_vertex_array, sdl_gl_delete_vertex_array, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_depth_func(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_depth_func(a0: i32) {
    ash_host_sdl_gl_depth_func(a0);
}
define_prim!(hlp_gl_depth_func, sdl_gl_depth_func, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_depth_mask(a0: i32);
}

/// `Pb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_depth_mask(a0: bool) {
    ash_host_sdl_gl_depth_mask(a0 as i32);
}
define_prim!(hlp_gl_depth_mask, sdl_gl_depth_mask, "Pb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_disable(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_disable(a0: i32) {
    ash_host_sdl_gl_disable(a0);
}
define_prim!(hlp_gl_disable, sdl_gl_disable, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_disable_vertex_attrib_array(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_disable_vertex_attrib_array(a0: i32) {
    ash_host_sdl_gl_disable_vertex_attrib_array(a0);
}
define_prim!(hlp_gl_disable_vertex_attrib_array, sdl_gl_disable_vertex_attrib_array, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_dispatch_compute(a0: i32, a1: i32, a2: i32);
}

/// `Piii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_dispatch_compute(a0: i32, a1: i32, a2: i32) {
    ash_host_sdl_gl_dispatch_compute(a0, a1, a2);
}
define_prim!(hlp_gl_dispatch_compute, sdl_gl_dispatch_compute, "Piii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_draw_arrays(a0: i32, a1: i32, a2: i32);
}

/// `Piii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_draw_arrays(a0: i32, a1: i32, a2: i32) {
    ash_host_sdl_gl_draw_arrays(a0, a1, a2);
}
define_prim!(hlp_gl_draw_arrays, sdl_gl_draw_arrays, "Piii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_draw_arrays_instanced(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_draw_arrays_instanced(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_draw_arrays_instanced(a0, a1, a2, a3);
}
define_prim!(hlp_gl_draw_arrays_instanced, sdl_gl_draw_arrays_instanced, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_draw_buffers(a0: i32, a1: i32);
}

/// `PiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_draw_buffers(a0: i32, a1: *mut vbyte) {
    ash_host_sdl_gl_draw_buffers(a0, a1 as i32);
}
define_prim!(hlp_gl_draw_buffers, sdl_gl_draw_buffers, "PiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_draw_elements(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_draw_elements(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_draw_elements(a0, a1, a2, a3);
}
define_prim!(hlp_gl_draw_elements, sdl_gl_draw_elements, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_draw_elements_instanced(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `Piiiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_draw_elements_instanced(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32) {
    ash_host_sdl_gl_draw_elements_instanced(a0, a1, a2, a3, a4);
}
define_prim!(hlp_gl_draw_elements_instanced, sdl_gl_draw_elements_instanced, "Piiiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_enable(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_enable(a0: i32) {
    ash_host_sdl_gl_enable(a0);
}
define_prim!(hlp_gl_enable, sdl_gl_enable, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_enable_vertex_attrib_array(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_enable_vertex_attrib_array(a0: i32) {
    ash_host_sdl_gl_enable_vertex_attrib_array(a0);
}
define_prim!(hlp_gl_enable_vertex_attrib_array, sdl_gl_enable_vertex_attrib_array, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_end_query(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_end_query(a0: i32) {
    ash_host_sdl_gl_end_query(a0);
}
define_prim!(hlp_gl_end_query, sdl_gl_end_query, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_finish();
}

/// `P_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_finish() {
    ash_host_sdl_gl_finish();
}
define_prim!(hlp_gl_finish, sdl_gl_finish, "P_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_framebuffer_renderbuffer(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `PiiiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_framebuffer_renderbuffer(a0: i32, a1: i32, a2: i32, a3: *mut vdynamic) {
    ash_host_sdl_gl_framebuffer_renderbuffer(a0, a1, a2, unbox_i32(a3));
}
define_prim!(hlp_gl_framebuffer_renderbuffer, sdl_gl_framebuffer_renderbuffer, "PiiiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_framebuffer_texture(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `PiiNii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_framebuffer_texture(a0: i32, a1: i32, a2: *mut vdynamic, a3: i32) {
    ash_host_sdl_gl_framebuffer_texture(a0, a1, unbox_i32(a2), a3);
}
define_prim!(hlp_gl_framebuffer_texture, sdl_gl_framebuffer_texture, "PiiNii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_framebuffer_texture2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `PiiiNii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_framebuffer_texture2d(a0: i32, a1: i32, a2: i32, a3: *mut vdynamic, a4: i32) {
    ash_host_sdl_gl_framebuffer_texture2d(a0, a1, a2, unbox_i32(a3), a4);
}
define_prim!(hlp_gl_framebuffer_texture2d, sdl_gl_framebuffer_texture2d, "PiiiNii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_framebuffer_texture_layer(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `PiiNiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_framebuffer_texture_layer(a0: i32, a1: i32, a2: *mut vdynamic, a3: i32, a4: i32) {
    ash_host_sdl_gl_framebuffer_texture_layer(a0, a1, unbox_i32(a2), a3, a4);
}
define_prim!(hlp_gl_framebuffer_texture_layer, sdl_gl_framebuffer_texture_layer, "PiiNiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_generate_mipmap(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_generate_mipmap(a0: i32) {
    ash_host_sdl_gl_generate_mipmap(a0);
}
define_prim!(hlp_gl_generate_mipmap, sdl_gl_generate_mipmap, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_attrib_location(a0: i32, a1: i32, a2: i32) -> i32;
}

/// `PNiOBi__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_attrib_location(a0: *mut vdynamic, a1: *mut vstring) -> i32 {
    ash_host_sdl_gl_get_attrib_location(unbox_i32(a0), string_bytes(a1), string_length(a1))
}
define_prim!(hlp_gl_get_attrib_location, sdl_gl_get_attrib_location, "PNiOBi__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_config_parameter(a0: i32) -> i32;
}

/// `Pi_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_config_parameter(a0: i32) -> i32 {
    ash_host_sdl_gl_get_config_parameter(a0)
}
define_prim!(hlp_gl_get_config_parameter, sdl_gl_get_config_parameter, "Pi_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_error() -> i32;
}

/// `P_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_error() -> i32 {
    ash_host_sdl_gl_get_error()
}
define_prim!(hlp_gl_get_error, sdl_gl_get_error, "P_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_program_info_bytes(a0: i32) -> i32;
}

/// `PNi_B`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_program_info_bytes(a0: *mut vdynamic) -> *mut vbyte {
    ash_host_sdl_gl_get_program_info_bytes(unbox_i32(a0)) as *mut vbyte
}
define_prim!(hlp_gl_get_program_info_bytes, sdl_gl_get_program_info_bytes, "PNi_B");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_program_parameter(a0: i32, a1: i32) -> i32;
}

/// `PNii_D`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_program_parameter(a0: *mut vdynamic, a1: i32) -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_get_program_parameter(unbox_i32(a0), a1))
}
define_prim!(hlp_gl_get_program_parameter, sdl_gl_get_program_parameter, "PNii_D");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_program_resource_index(a0: i32, a1: i32, a2: i32, a3: i32) -> i32;
}

/// `PNiiOBi__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_program_resource_index(a0: *mut vdynamic, a1: i32, a2: *mut vstring) -> i32 {
    ash_host_sdl_gl_get_program_resource_index(unbox_i32(a0), a1, string_bytes(a2), string_length(a2))
}
define_prim!(hlp_gl_get_program_resource_index, sdl_gl_get_program_resource_index, "PNiiOBi__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_shader_info_bytes(a0: i32) -> i32;
}

/// `PNi_B`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_shader_info_bytes(a0: *mut vdynamic) -> *mut vbyte {
    ash_host_sdl_gl_get_shader_info_bytes(unbox_i32(a0)) as *mut vbyte
}
define_prim!(hlp_gl_get_shader_info_bytes, sdl_gl_get_shader_info_bytes, "PNi_B");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_shader_parameter(a0: i32, a1: i32) -> i32;
}

/// `PNii_D`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_shader_parameter(a0: *mut vdynamic, a1: i32) -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_get_shader_parameter(unbox_i32(a0), a1))
}
define_prim!(hlp_gl_get_shader_parameter, sdl_gl_get_shader_parameter, "PNii_D");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_uniform_block_index(a0: i32, a1: i32, a2: i32) -> i32;
}

/// `PNiOBi__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_uniform_block_index(a0: *mut vdynamic, a1: *mut vstring) -> i32 {
    ash_host_sdl_gl_get_uniform_block_index(unbox_i32(a0), string_bytes(a1), string_length(a1))
}
define_prim!(hlp_gl_get_uniform_block_index, sdl_gl_get_uniform_block_index, "PNiOBi__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_uniform_location(a0: i32, a1: i32, a2: i32) -> i32;
}

/// `PNiOBi__Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_uniform_location(a0: *mut vdynamic, a1: *mut vstring) -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_get_uniform_location(unbox_i32(a0), string_bytes(a1), string_length(a1)))
}
define_prim!(hlp_gl_get_uniform_location, sdl_gl_get_uniform_location, "PNiOBi__Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_has_extension(a0: i32, a1: i32) -> i32;
}

/// `POBi__b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_has_extension(a0: *mut vstring) -> bool {
    ash_host_sdl_gl_has_extension(string_bytes(a0), string_length(a0)) != 0
}
define_prim!(hlp_gl_has_extension, sdl_gl_has_extension, "POBi__b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_init() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_init() -> bool {
    ash_host_sdl_gl_init() != 0
}
define_prim!(hlp_gl_init, sdl_gl_init, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_is_context_lost() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_is_context_lost() -> bool {
    ash_host_sdl_gl_is_context_lost() != 0
}
define_prim!(hlp_gl_is_context_lost, sdl_gl_is_context_lost, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_link_program(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_link_program(a0: *mut vdynamic) {
    ash_host_sdl_gl_link_program(unbox_i32(a0));
}
define_prim!(hlp_gl_link_program, sdl_gl_link_program, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_memory_barrier(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_memory_barrier(a0: i32) {
    ash_host_sdl_gl_memory_barrier(a0);
}
define_prim!(hlp_gl_memory_barrier, sdl_gl_memory_barrier, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_multi_draw_elements_indirect(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `PiiBii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_multi_draw_elements_indirect(a0: i32, a1: i32, a2: *mut vbyte, a3: i32, a4: i32) {
    ash_host_sdl_gl_multi_draw_elements_indirect(a0, a1, a2 as i32, a3, a4);
}
define_prim!(hlp_gl_multi_draw_elements_indirect, sdl_gl_multi_draw_elements_indirect, "PiiBii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_multi_draw_elements_indirect_count(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32);
}

/// `PiiBBii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_multi_draw_elements_indirect_count(a0: i32, a1: i32, a2: *mut vbyte, a3: *mut vbyte, a4: i32, a5: i32) {
    ash_host_sdl_gl_multi_draw_elements_indirect_count(a0, a1, a2 as i32, a3 as i32, a4, a5);
}
define_prim!(hlp_gl_multi_draw_elements_indirect_count, sdl_gl_multi_draw_elements_indirect_count, "PiiBBii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_options(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32);
}

/// `Piiiiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_options(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32) {
    ash_host_sdl_gl_options(a0, a1, a2, a3, a4, a5);
}
define_prim!(hlp_gl_options, sdl_gl_options, "Piiiiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_pixel_storei(a0: i32, a1: i32);
}

/// `Pii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_pixel_storei(a0: i32, a1: i32) {
    ash_host_sdl_gl_pixel_storei(a0, a1);
}
define_prim!(hlp_gl_pixel_storei, sdl_gl_pixel_storei, "Pii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_polygon_mode(a0: i32, a1: i32);
}

/// `Pii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_polygon_mode(a0: i32, a1: i32) {
    ash_host_sdl_gl_polygon_mode(a0, a1);
}
define_prim!(hlp_gl_polygon_mode, sdl_gl_polygon_mode, "Pii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_polygon_offset(a0: f64, a1: f64);
}

/// `Pff_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_polygon_offset(a0: f32, a1: f32) {
    ash_host_sdl_gl_polygon_offset(a0 as f64, a1 as f64);
}
define_prim!(hlp_gl_polygon_offset, sdl_gl_polygon_offset, "Pff_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_query_counter(a0: i32, a1: i32);
}

/// `PNii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_query_counter(a0: *mut vdynamic, a1: i32) {
    ash_host_sdl_gl_query_counter(unbox_i32(a0), a1);
}
define_prim!(hlp_gl_query_counter, sdl_gl_query_counter, "PNii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_query_result(a0: i32) -> f64;
}

/// `PNi_d`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_query_result(a0: *mut vdynamic) -> f64 {
    ash_host_sdl_gl_query_result(unbox_i32(a0))
}
define_prim!(hlp_gl_query_result, sdl_gl_query_result, "PNi_d");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_query_result_available(a0: i32) -> i32;
}

/// `PNi_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_query_result_available(a0: *mut vdynamic) -> bool {
    ash_host_sdl_gl_query_result_available(unbox_i32(a0)) != 0
}
define_prim!(hlp_gl_query_result_available, sdl_gl_query_result_available, "PNi_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_read_buffer(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_read_buffer(a0: i32) {
    ash_host_sdl_gl_read_buffer(a0);
}
define_prim!(hlp_gl_read_buffer, sdl_gl_read_buffer, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_read_pixels(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32);
}

/// `PiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_read_pixels(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: *mut vbyte) {
    ash_host_sdl_gl_read_pixels(a0, a1, a2, a3, a4, a5, a6 as i32);
}
define_prim!(hlp_gl_read_pixels, sdl_gl_read_pixels, "PiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_renderbuffer_storage(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_renderbuffer_storage(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_renderbuffer_storage(a0, a1, a2, a3);
}
define_prim!(hlp_gl_renderbuffer_storage, sdl_gl_renderbuffer_storage, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_renderbuffer_storage_multisample(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `Piiiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_renderbuffer_storage_multisample(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32) {
    ash_host_sdl_gl_renderbuffer_storage_multisample(a0, a1, a2, a3, a4);
}
define_prim!(hlp_gl_renderbuffer_storage_multisample, sdl_gl_renderbuffer_storage_multisample, "Piiiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_scissor(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_scissor(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_scissor(a0, a1, a2, a3);
}
define_prim!(hlp_gl_scissor, sdl_gl_scissor, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_shader_source(a0: i32, a1: i32, a2: i32);
}

/// `PNiOBi__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_shader_source(a0: *mut vdynamic, a1: *mut vstring) {
    ash_host_sdl_gl_shader_source(unbox_i32(a0), string_bytes(a1), string_length(a1));
}
define_prim!(hlp_gl_shader_source, sdl_gl_shader_source, "PNiOBi__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_shader_storage_block_binding(a0: i32, a1: i32, a2: i32);
}

/// `PNiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_shader_storage_block_binding(a0: *mut vdynamic, a1: i32, a2: i32) {
    ash_host_sdl_gl_shader_storage_block_binding(unbox_i32(a0), a1, a2);
}
define_prim!(hlp_gl_shader_storage_block_binding, sdl_gl_shader_storage_block_binding, "PNiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_stencil_func_separate(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_stencil_func_separate(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_stencil_func_separate(a0, a1, a2, a3);
}
define_prim!(hlp_gl_stencil_func_separate, sdl_gl_stencil_func_separate, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_stencil_mask_separate(a0: i32, a1: i32);
}

/// `Pii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_stencil_mask_separate(a0: i32, a1: i32) {
    ash_host_sdl_gl_stencil_mask_separate(a0, a1);
}
define_prim!(hlp_gl_stencil_mask_separate, sdl_gl_stencil_mask_separate, "Pii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_stencil_op_separate(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_stencil_op_separate(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_stencil_op_separate(a0, a1, a2, a3);
}
define_prim!(hlp_gl_stencil_op_separate, sdl_gl_stencil_op_separate, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32);
}

/// `PiiiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: *mut vbyte) {
    ash_host_sdl_gl_tex_image2d(a0, a1, a2, a3, a4, a5, a6, a7, a8 as i32);
}
define_prim!(hlp_gl_tex_image2d, sdl_gl_tex_image2d, "PiiiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_image2d_multisample(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32);
}

/// `Piiiiib_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_image2d_multisample(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: bool) {
    ash_host_sdl_gl_tex_image2d_multisample(a0, a1, a2, a3, a4, a5 as i32);
}
define_prim!(hlp_gl_tex_image2d_multisample, sdl_gl_tex_image2d_multisample, "Piiiiib_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_image3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32);
}

/// `PiiiiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_image3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: *mut vbyte) {
    ash_host_sdl_gl_tex_image3d(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9 as i32);
}
define_prim!(hlp_gl_tex_image3d, sdl_gl_tex_image3d, "PiiiiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_parameterf(a0: i32, a1: i32, a2: f64);
}

/// `Piif_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_parameterf(a0: i32, a1: i32, a2: f32) {
    ash_host_sdl_gl_tex_parameterf(a0, a1, a2 as f64);
}
define_prim!(hlp_gl_tex_parameterf, sdl_gl_tex_parameterf, "Piif_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_parameteri(a0: i32, a1: i32, a2: i32);
}

/// `Piii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_parameteri(a0: i32, a1: i32, a2: i32) {
    ash_host_sdl_gl_tex_parameteri(a0, a1, a2);
}
define_prim!(hlp_gl_tex_parameteri, sdl_gl_tex_parameteri, "Piii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_storage2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `Piiiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_storage2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32) {
    ash_host_sdl_gl_tex_storage2d(a0, a1, a2, a3, a4);
}
define_prim!(hlp_gl_tex_storage2d, sdl_gl_tex_storage2d, "Piiiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_storage3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32);
}

/// `Piiiiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_storage3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32) {
    ash_host_sdl_gl_tex_storage3d(a0, a1, a2, a3, a4, a5);
}
define_prim!(hlp_gl_tex_storage3d, sdl_gl_tex_storage3d, "Piiiiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_sub_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32);
}

/// `PiiiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_sub_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: *mut vbyte) {
    ash_host_sdl_gl_tex_sub_image2d(a0, a1, a2, a3, a4, a5, a6, a7, a8 as i32);
}
define_prim!(hlp_gl_tex_sub_image2d, sdl_gl_tex_sub_image2d, "PiiiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_sub_image3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32, a10: i32);
}

/// `PiiiiiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_sub_image3d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32, a10: *mut vbyte) {
    ash_host_sdl_gl_tex_sub_image3d(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10 as i32);
}
define_prim!(hlp_gl_tex_sub_image3d, sdl_gl_tex_sub_image3d, "PiiiiiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_uniform1i(a0: i32, a1: i32);
}

/// `PNii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_uniform1i(a0: *mut vdynamic, a1: i32) {
    ash_host_sdl_gl_uniform1i(unbox_i32(a0), a1);
}
define_prim!(hlp_gl_uniform1i, sdl_gl_uniform1i, "PNii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_uniform4fv(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `PNiBii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_uniform4fv(a0: *mut vdynamic, a1: *mut vbyte, a2: i32, a3: i32) {
    ash_host_sdl_gl_uniform4fv(unbox_i32(a0), a1 as i32, a2, a3);
}
define_prim!(hlp_gl_uniform4fv, sdl_gl_uniform4fv, "PNiBii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_uniform_block_binding(a0: i32, a1: i32, a2: i32);
}

/// `PNiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_uniform_block_binding(a0: *mut vdynamic, a1: i32, a2: i32) {
    ash_host_sdl_gl_uniform_block_binding(unbox_i32(a0), a1, a2);
}
define_prim!(hlp_gl_uniform_block_binding, sdl_gl_uniform_block_binding, "PNiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_uniform_matrix4fv(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `PNibBii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_uniform_matrix4fv(a0: *mut vdynamic, a1: bool, a2: *mut vbyte, a3: i32, a4: i32) {
    ash_host_sdl_gl_uniform_matrix4fv(unbox_i32(a0), a1 as i32, a2 as i32, a3, a4);
}
define_prim!(hlp_gl_uniform_matrix4fv, sdl_gl_uniform_matrix4fv, "PNibBii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_use_program(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_use_program(a0: *mut vdynamic) {
    ash_host_sdl_gl_use_program(unbox_i32(a0));
}
define_prim!(hlp_gl_use_program, sdl_gl_use_program, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_vertex_attrib_divisor(a0: i32, a1: i32);
}

/// `Pii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_vertex_attrib_divisor(a0: i32, a1: i32) {
    ash_host_sdl_gl_vertex_attrib_divisor(a0, a1);
}
define_prim!(hlp_gl_vertex_attrib_divisor, sdl_gl_vertex_attrib_divisor, "Pii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_vertex_attrib_ipointer(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `Piiiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_vertex_attrib_ipointer(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32) {
    ash_host_sdl_gl_vertex_attrib_ipointer(a0, a1, a2, a3, a4);
}
define_prim!(hlp_gl_vertex_attrib_ipointer, sdl_gl_vertex_attrib_ipointer, "Piiiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_vertex_attrib_pointer(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32);
}

/// `Piiibii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_vertex_attrib_pointer(a0: i32, a1: i32, a2: i32, a3: bool, a4: i32, a5: i32) {
    ash_host_sdl_gl_vertex_attrib_pointer(a0, a1, a2, a3 as i32, a4, a5);
}
define_prim!(hlp_gl_vertex_attrib_pointer, sdl_gl_vertex_attrib_pointer, "Piiibii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_viewport(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_viewport(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_viewport(a0, a1, a2, a3);
}
define_prim!(hlp_gl_viewport, sdl_gl_viewport, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_haptic_close(a0: i32);
}

/// `PXsdl_haptic__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_haptic_close(a0: *mut c_void) {
    ash_host_sdl_haptic_close(a0 as i32);
}
define_prim!(hlp_haptic_close, sdl_haptic_close, "PXsdl_haptic__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_haptic_open(a0: i32) -> i32;
}

/// `PXsdl_gamecontroller__Xsdl_haptic_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_haptic_open(a0: *mut c_void) -> *mut c_void {
    ash_host_sdl_haptic_open(a0 as i32) as *mut c_void
}
define_prim!(hlp_haptic_open, sdl_haptic_open, "PXsdl_gamecontroller__Xsdl_haptic_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_haptic_rumble_init(a0: i32) -> i32;
}

/// `PXsdl_haptic__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_haptic_rumble_init(a0: *mut c_void) -> i32 {
    ash_host_sdl_haptic_rumble_init(a0 as i32)
}
define_prim!(hlp_haptic_rumble_init, sdl_haptic_rumble_init, "PXsdl_haptic__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_haptic_rumble_play(a0: i32, a1: f64, a2: i32) -> i32;
}

/// `PXsdl_haptic_di_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_haptic_rumble_play(a0: *mut c_void, a1: f64, a2: i32) -> i32 {
    ash_host_sdl_haptic_rumble_play(a0 as i32, a1, a2)
}
define_prim!(hlp_haptic_rumble_play, sdl_haptic_rumble_play, "PXsdl_haptic_di_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_hint_value(a0: i32, a1: i32) -> i32;
}

/// `PBB_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_hint_value(a0: *mut vbyte, a1: *mut vbyte) -> bool {
    ash_host_sdl_hint_value(a0 as i32, a1 as i32) != 0
}
define_prim!(hlp_hint_value, sdl_hint_value, "PBB_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_init_once() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_init_once() -> bool {
    ash_host_sdl_init_once() != 0
}
define_prim!(hlp_init_once, sdl_init_once, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_is_cursor_visible() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_is_cursor_visible() -> bool {
    ash_host_sdl_is_cursor_visible() != 0
}
define_prim!(hlp_is_cursor_visible, sdl_is_cursor_visible, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_message_box(a0: i32, a1: i32, a2: i32);
}

/// `PBBb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_message_box(a0: *mut vbyte, a1: *mut vbyte, a2: bool) {
    ash_host_sdl_message_box(a0 as i32, a1 as i32, a2 as i32);
}
define_prim!(hlp_message_box, sdl_message_box, "PBBb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_quit();
}

/// `P_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_quit() {
    ash_host_sdl_quit();
}
define_prim!(hlp_quit, sdl_quit, "P_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_set_clipboard_text(a0: i32) -> i32;
}

/// `PB_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_set_clipboard_text(a0: *mut vbyte) -> bool {
    ash_host_sdl_set_clipboard_text(a0 as i32) != 0
}
define_prim!(hlp_set_clipboard_text, sdl_set_clipboard_text, "PB_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_set_cursor(a0: i32);
}

/// `PXsdl_cursor__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_set_cursor(a0: *mut c_void) {
    ash_host_sdl_set_cursor(a0 as i32);
}
define_prim!(hlp_set_cursor, sdl_set_cursor, "PXsdl_cursor__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_set_drag_and_drop_enabled(a0: i32);
}

/// `Pb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_set_drag_and_drop_enabled(a0: bool) {
    ash_host_sdl_set_drag_and_drop_enabled(a0 as i32);
}
define_prim!(hlp_set_drag_and_drop_enabled, sdl_set_drag_and_drop_enabled, "Pb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_set_relative_mouse_mode(a0: i32) -> i32;
}

/// `Pb_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_set_relative_mouse_mode(a0: bool) -> i32 {
    ash_host_sdl_set_relative_mouse_mode(a0 as i32)
}
define_prim!(hlp_set_relative_mouse_mode, sdl_set_relative_mouse_mode, "Pb_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_set_vsync(a0: i32);
}

/// `Pb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_set_vsync(a0: bool) {
    ash_host_sdl_set_vsync(a0 as i32);
}
define_prim!(hlp_set_vsync, sdl_set_vsync, "Pb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_set_window_grab(a0: i32, a1: i32);
}

/// `PXsdl_window_b_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_set_window_grab(a0: *mut c_void, a1: bool) {
    ash_host_sdl_set_window_grab(a0 as i32, a1 as i32);
}
define_prim!(hlp_set_window_grab, sdl_set_window_grab, "PXsdl_window_b_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_show_cursor(a0: i32);
}

/// `Pb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_show_cursor(a0: bool) {
    ash_host_sdl_show_cursor(a0 as i32);
}
define_prim!(hlp_show_cursor, sdl_show_cursor, "Pb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_surface_from(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32) -> i32;
}

/// `PBiiiiiiii_Xsdl_surface_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_surface_from(a0: *mut vbyte, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32) -> *mut c_void {
    ash_host_sdl_surface_from(a0 as i32, a1, a2, a3, a4, a5, a6, a7, a8) as *mut c_void
}
define_prim!(hlp_surface_from, sdl_surface_from, "PBiiiiiiii_Xsdl_surface_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_warp_mouse_global(a0: i32, a1: i32) -> i32;
}

/// `Pii_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_warp_mouse_global(a0: i32, a1: i32) -> i32 {
    ash_host_sdl_warp_mouse_global(a0, a1)
}
define_prim!(hlp_warp_mouse_global, sdl_warp_mouse_global, "Pii_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_warp_mouse_in_window(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_ii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_warp_mouse_in_window(a0: *mut c_void, a1: i32, a2: i32) {
    ash_host_sdl_warp_mouse_in_window(a0 as i32, a1, a2);
}
define_prim!(hlp_warp_mouse_in_window, sdl_warp_mouse_in_window, "PXsdl_window_ii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_create(a0: i32, a1: i32) -> i32;
}

/// `Pii_Xsdl_window_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_create(a0: i32, a1: i32) -> *mut c_void {
    ash_host_sdl_win_create(a0, a1) as *mut c_void
}
define_prim!(hlp_win_create, sdl_win_create, "Pii_Xsdl_window_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_create_ex(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32) -> i32;
}

/// `Piiiii_Xsdl_window_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_create_ex(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32) -> *mut c_void {
    ash_host_sdl_win_create_ex(a0, a1, a2, a3, a4) as *mut c_void
}
define_prim!(hlp_win_create_ex, sdl_win_create_ex, "Piiiii_Xsdl_window_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_destroy(a0: i32, a1: i32);
}

/// `PXsdl_window_Xsdl_gl__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_destroy(a0: *mut c_void, a1: *mut c_void) {
    ash_host_sdl_win_destroy(a0 as i32, a1 as i32);
}
define_prim!(hlp_win_destroy, sdl_win_destroy, "PXsdl_window_Xsdl_gl__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_display_handle(a0: i32) -> i32;
}

/// `PXsdl_window__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_display_handle(a0: *mut c_void) -> i32 {
    ash_host_sdl_win_display_handle(a0 as i32)
}
define_prim!(hlp_win_display_handle, sdl_win_display_handle, "PXsdl_window__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_get_glcontext(a0: i32) -> i32;
}

/// `PXsdl_window__Xsdl_gl_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_get_glcontext(a0: *mut c_void) -> *mut c_void {
    ash_host_sdl_win_get_glcontext(a0 as i32) as *mut c_void
}
define_prim!(hlp_win_get_glcontext, sdl_win_get_glcontext, "PXsdl_window__Xsdl_gl_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_get_id(a0: i32) -> i32;
}

/// `PXsdl_window__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_get_id(a0: *mut c_void) -> i32 {
    ash_host_sdl_win_get_id(a0 as i32)
}
define_prim!(hlp_win_get_id, sdl_win_get_id, "PXsdl_window__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_get_max_size(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_RiRi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_get_max_size(a0: *mut c_void, a1: *mut i32, a2: *mut i32) {
    ash_host_sdl_win_get_max_size(a0 as i32, a1 as i32, a2 as i32);
}
define_prim!(hlp_win_get_max_size, sdl_win_get_max_size, "PXsdl_window_RiRi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_get_min_size(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_RiRi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_get_min_size(a0: *mut c_void, a1: *mut i32, a2: *mut i32) {
    ash_host_sdl_win_get_min_size(a0 as i32, a1 as i32, a2 as i32);
}
define_prim!(hlp_win_get_min_size, sdl_win_get_min_size, "PXsdl_window_RiRi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_get_opacity(a0: i32) -> f64;
}

/// `PXsdl_window__d`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_get_opacity(a0: *mut c_void) -> f64 {
    ash_host_sdl_win_get_opacity(a0 as i32)
}
define_prim!(hlp_win_get_opacity, sdl_win_get_opacity, "PXsdl_window__d");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_get_position(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_RiRi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_get_position(a0: *mut c_void, a1: *mut i32, a2: *mut i32) {
    ash_host_sdl_win_get_position(a0 as i32, a1 as i32, a2 as i32);
}
define_prim!(hlp_win_get_position, sdl_win_get_position, "PXsdl_window_RiRi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_get_size(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_RiRi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_get_size(a0: *mut c_void, a1: *mut i32, a2: *mut i32) {
    ash_host_sdl_win_get_size(a0 as i32, a1 as i32, a2 as i32);
}
define_prim!(hlp_win_get_size, sdl_win_get_size, "PXsdl_window_RiRi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_render_to(a0: i32, a1: i32);
}

/// `PXsdl_window_Xsdl_gl__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_render_to(a0: *mut c_void, a1: *mut c_void) {
    ash_host_sdl_win_render_to(a0 as i32, a1 as i32);
}
define_prim!(hlp_win_render_to, sdl_win_render_to, "PXsdl_window_Xsdl_gl__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_resize(a0: i32, a1: i32);
}

/// `PXsdl_window_i_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_resize(a0: *mut c_void, a1: i32) {
    ash_host_sdl_win_resize(a0 as i32, a1);
}
define_prim!(hlp_win_resize, sdl_win_resize, "PXsdl_window_i_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_display_mode(a0: i32, a1: i32, a2: i32, a3: i32) -> i32;
}

/// `PXsdl_window_iii_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_display_mode(a0: *mut c_void, a1: i32, a2: i32, a3: i32) -> bool {
    ash_host_sdl_win_set_display_mode(a0 as i32, a1, a2, a3) != 0
}
define_prim!(hlp_win_set_display_mode, sdl_win_set_display_mode, "PXsdl_window_iii_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_fullscreen(a0: i32, a1: i32) -> i32;
}

/// `PXsdl_window_i_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_fullscreen(a0: *mut c_void, a1: i32) -> bool {
    ash_host_sdl_win_set_fullscreen(a0 as i32, a1) != 0
}
define_prim!(hlp_win_set_fullscreen, sdl_win_set_fullscreen, "PXsdl_window_i_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_max_size(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_ii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_max_size(a0: *mut c_void, a1: i32, a2: i32) {
    ash_host_sdl_win_set_max_size(a0 as i32, a1, a2);
}
define_prim!(hlp_win_set_max_size, sdl_win_set_max_size, "PXsdl_window_ii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_min_size(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_ii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_min_size(a0: *mut c_void, a1: i32, a2: i32) {
    ash_host_sdl_win_set_min_size(a0 as i32, a1, a2);
}
define_prim!(hlp_win_set_min_size, sdl_win_set_min_size, "PXsdl_window_ii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_opacity(a0: i32, a1: f64) -> i32;
}

/// `PXsdl_window_d_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_opacity(a0: *mut c_void, a1: f64) -> bool {
    ash_host_sdl_win_set_opacity(a0 as i32, a1) != 0
}
define_prim!(hlp_win_set_opacity, sdl_win_set_opacity, "PXsdl_window_d_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_position(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_ii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_position(a0: *mut c_void, a1: i32, a2: i32) {
    ash_host_sdl_win_set_position(a0 as i32, a1, a2);
}
define_prim!(hlp_win_set_position, sdl_win_set_position, "PXsdl_window_ii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_size(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_ii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_size(a0: *mut c_void, a1: i32, a2: i32) {
    ash_host_sdl_win_set_size(a0 as i32, a1, a2);
}
define_prim!(hlp_win_set_size, sdl_win_set_size, "PXsdl_window_ii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_title(a0: i32, a1: i32);
}

/// `PXsdl_window_B_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_title(a0: *mut c_void, a1: *mut vbyte) {
    ash_host_sdl_win_set_title(a0 as i32, a1 as i32);
}
define_prim!(hlp_win_set_title, sdl_win_set_title, "PXsdl_window_B_v");
