//! The `sdl` library for wasm: every primitive the Heaps base3d example
//! reaches, forwarding to the host.
//!
//! GENERATED by `scripts/generate_sdl_shim.py` from the signatures `sdl.hdll`
//! reports for itself. Edit the generator, not this file.
//!
//! Nothing here decides anything. A window, a GL context and a frame belong
//! to whoever is embedding the program -- a canvas in a page, or a recorder
//! under a headless host -- so every function is the same shape: unwrap what
//! HashLink boxed, hand the plain values to the host, box whatever comes
//! back.

use std::ffi::c_void;

// Not every library needs all of it: `ui` boxes nothing.
#[allow(unused_imports)]
use crate::abi::*;


#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_button_new(a0: i32, a1: i32, a2: i32) -> i32;
}

/// `PXui_window_BP_v_Xui_window_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_button_new(a0: *mut c_void, a1: *mut vbyte, a2: *mut c_void) -> *mut c_void {
    ash_host_ui_ui_button_new(a0 as i32, a1 as i32, a2 as i32) as *mut c_void
}
define_prim!(hlp_ui_button_new, sdl_ui_button_new, "PXui_window_BP_v_Xui_window_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_choose_file(a0: i32, a1: i32) -> i32;
}

/// `PbD_B`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_choose_file(a0: bool, a1: *mut vdynamic) -> *mut vbyte {
    ash_host_ui_ui_choose_file(a0 as i32, a1 as i32) as *mut vbyte
}
define_prim!(hlp_ui_choose_file, sdl_ui_choose_file, "PbD_B");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_dialog(a0: i32, a1: i32, a2: i32) -> i32;
}

/// `PBBi_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_dialog(a0: *mut vbyte, a1: *mut vbyte, a2: i32) -> i32 {
    ash_host_ui_ui_dialog(a0 as i32, a1 as i32, a2)
}
define_prim!(hlp_ui_dialog, sdl_ui_dialog, "PBBi_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_init();
}

/// `P_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_init() {
    ash_host_ui_ui_init();
}
define_prim!(hlp_ui_init, sdl_ui_init, "P_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_loop(a0: i32) -> i32;
}

/// `Pb_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_loop(a0: bool) -> i32 {
    ash_host_ui_ui_loop(a0 as i32)
}
define_prim!(hlp_ui_loop, sdl_ui_loop, "Pb_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_sentinel_is_paused(a0: i32) -> i32;
}

/// `PXui_sentinel__b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_sentinel_is_paused(a0: *mut c_void) -> bool {
    ash_host_ui_ui_sentinel_is_paused(a0 as i32) != 0
}
define_prim!(hlp_ui_sentinel_is_paused, sdl_ui_sentinel_is_paused, "PXui_sentinel__b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_sentinel_pause(a0: i32, a1: i32);
}

/// `PXui_sentinel_b_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_sentinel_pause(a0: *mut c_void, a1: bool) {
    ash_host_ui_ui_sentinel_pause(a0 as i32, a1 as i32);
}
define_prim!(hlp_ui_sentinel_pause, sdl_ui_sentinel_pause, "PXui_sentinel_b_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_sentinel_tick(a0: i32);
}

/// `PXui_sentinel__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_sentinel_tick(a0: *mut c_void) {
    ash_host_ui_ui_sentinel_tick(a0 as i32);
}
define_prim!(hlp_ui_sentinel_tick, sdl_ui_sentinel_tick, "PXui_sentinel__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_start_sentinel(a0: f64, a1: i32) -> i32;
}

/// `PdP_v_Xui_sentinel_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_start_sentinel(a0: f64, a1: *mut c_void) -> *mut c_void {
    ash_host_ui_ui_start_sentinel(a0, a1 as i32) as *mut c_void
}
define_prim!(hlp_ui_start_sentinel, sdl_ui_start_sentinel, "PdP_v_Xui_sentinel_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_stop_loop();
}

/// `P_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_stop_loop() {
    ash_host_ui_ui_stop_loop();
}
define_prim!(hlp_ui_stop_loop, sdl_ui_stop_loop, "P_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_win_destroy(a0: i32);
}

/// `PXui_window__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_win_destroy(a0: *mut c_void) {
    ash_host_ui_ui_win_destroy(a0 as i32);
}
define_prim!(hlp_ui_win_destroy, sdl_ui_win_destroy, "PXui_window__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_winlog_new(a0: i32, a1: i32, a2: i32) -> i32;
}

/// `PBii_Xui_window_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_winlog_new(a0: *mut vbyte, a1: i32, a2: i32) -> *mut c_void {
    ash_host_ui_ui_winlog_new(a0 as i32, a1, a2) as *mut c_void
}
define_prim!(hlp_ui_winlog_new, sdl_ui_winlog_new, "PBii_Xui_window_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_ui_ui_winlog_set_text(a0: i32, a1: i32, a2: i32);
}

/// `PXui_window_Bb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_ui_winlog_set_text(a0: *mut c_void, a1: *mut vbyte, a2: bool) {
    ash_host_ui_ui_winlog_set_text(a0 as i32, a1 as i32, a2 as i32);
}
define_prim!(hlp_ui_winlog_set_text, sdl_ui_winlog_set_text, "PXui_window_Bb_v");
