#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
// Generated by bindgen; its idioms are not ours to lint. The runtime-symbol
// lint fires on its c_ulong-vs-usize libc declarations, which are what
// bindgen emits for the platform headers.
#![allow(
    unknown_lints,
    unnecessary_transmutes,
    suspicious_runtime_symbol_definitions
)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/hl_bindings.rs"));
