//! The `sdl` library for wasm: every primitive the Heaps base3d example
//! reaches, forwarding to the host.
//!
//! GENERATED by `scripts/generate_sdl_shim.py` from the signatures `sdl.hdll`
//! reports for itself. Edit the generator, not this file.
//!
//! Nothing here decides anything. A window, a GL context and a frame belong
//! to whoever is embedding the program -- a canvas in a page, or a recorder
//! under a headless host -- so every function is the same shape: unwrap what
//! HashLink boxed, hand the plain values to the host, box whatever comes
//! back.

use std::ffi::c_void;

use crate::abi::*;


#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_detect_win32() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_detect_win32() -> bool {
    ash_host_sdl_detect_win32() != 0
}
define_prim!(hlp_detect_win32, sdl_detect_win32, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_event_loop(a0: i32) -> i32;
}

/// `PD_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_event_loop(a0: *mut vdynamic) -> bool {
    ash_host_sdl_event_loop(a0 as i32) != 0
}
define_prim!(hlp_event_loop, sdl_event_loop, "PD_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_active_texture(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_active_texture(a0: i32) {
    ash_host_sdl_gl_active_texture(a0);
}
define_prim!(hlp_gl_active_texture, sdl_gl_active_texture, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_attach_shader(a0: i32, a1: i32);
}

/// `PNiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_attach_shader(a0: *mut vdynamic, a1: *mut vdynamic) {
    ash_host_sdl_gl_attach_shader(unbox_i32(a0), unbox_i32(a1));
}
define_prim!(hlp_gl_attach_shader, sdl_gl_attach_shader, "PNiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_buffer(a0: i32, a1: i32);
}

/// `PiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_buffer(a0: i32, a1: *mut vdynamic) {
    ash_host_sdl_gl_bind_buffer(a0, unbox_i32(a1));
}
define_prim!(hlp_gl_bind_buffer, sdl_gl_bind_buffer, "PiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_frag_data_location(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `PNiiOBi__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_frag_data_location(a0: *mut vdynamic, a1: i32, a2: *mut vstring) {
    ash_host_sdl_gl_bind_frag_data_location(unbox_i32(a0), a1, string_bytes(a2), string_length(a2));
}
define_prim!(hlp_gl_bind_frag_data_location, sdl_gl_bind_frag_data_location, "PNiiOBi__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_framebuffer(a0: i32, a1: i32);
}

/// `PiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_framebuffer(a0: i32, a1: *mut vdynamic) {
    ash_host_sdl_gl_bind_framebuffer(a0, unbox_i32(a1));
}
define_prim!(hlp_gl_bind_framebuffer, sdl_gl_bind_framebuffer, "PiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_texture(a0: i32, a1: i32);
}

/// `PiNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_texture(a0: i32, a1: *mut vdynamic) {
    ash_host_sdl_gl_bind_texture(a0, unbox_i32(a1));
}
define_prim!(hlp_gl_bind_texture, sdl_gl_bind_texture, "PiNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_bind_vertex_array(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_bind_vertex_array(a0: *mut vdynamic) {
    ash_host_sdl_gl_bind_vertex_array(unbox_i32(a0));
}
define_prim!(hlp_gl_bind_vertex_array, sdl_gl_bind_vertex_array, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_blend_equation(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_blend_equation(a0: i32) {
    ash_host_sdl_gl_blend_equation(a0);
}
define_prim!(hlp_gl_blend_equation, sdl_gl_blend_equation, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_buffer_data_size(a0: i32, a1: i32, a2: i32);
}

/// `Piii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_buffer_data_size(a0: i32, a1: i32, a2: i32) {
    ash_host_sdl_gl_buffer_data_size(a0, a1, a2);
}
define_prim!(hlp_gl_buffer_data_size, sdl_gl_buffer_data_size, "Piii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_buffer_sub_data(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `PiiBii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_buffer_sub_data(a0: i32, a1: i32, a2: *mut vbyte, a3: i32, a4: i32) {
    ash_host_sdl_gl_buffer_sub_data(a0, a1, a2 as i32, a3, a4);
}
define_prim!(hlp_gl_buffer_sub_data, sdl_gl_buffer_sub_data, "PiiBii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_clear(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_clear(a0: i32) {
    ash_host_sdl_gl_clear(a0);
}
define_prim!(hlp_gl_clear, sdl_gl_clear, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_clear_color(a0: f64, a1: f64, a2: f64, a3: f64);
}

/// `Pdddd_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_clear_color(a0: f64, a1: f64, a2: f64, a3: f64) {
    ash_host_sdl_gl_clear_color(a0, a1, a2, a3);
}
define_prim!(hlp_gl_clear_color, sdl_gl_clear_color, "Pdddd_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_clear_depth(a0: f64);
}

/// `Pd_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_clear_depth(a0: f64) {
    ash_host_sdl_gl_clear_depth(a0);
}
define_prim!(hlp_gl_clear_depth, sdl_gl_clear_depth, "Pd_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_clear_stencil(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_clear_stencil(a0: i32) {
    ash_host_sdl_gl_clear_stencil(a0);
}
define_prim!(hlp_gl_clear_stencil, sdl_gl_clear_stencil, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_color_mask(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Pbbbb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_color_mask(a0: bool, a1: bool, a2: bool, a3: bool) {
    ash_host_sdl_gl_color_mask(a0 as i32, a1 as i32, a2 as i32, a3 as i32);
}
define_prim!(hlp_gl_color_mask, sdl_gl_color_mask, "Pbbbb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_compile_shader(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_compile_shader(a0: *mut vdynamic) {
    ash_host_sdl_gl_compile_shader(unbox_i32(a0));
}
define_prim!(hlp_gl_compile_shader, sdl_gl_compile_shader, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_buffer() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_buffer() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_buffer())
}
define_prim!(hlp_gl_create_buffer, sdl_gl_create_buffer, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_framebuffer() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_framebuffer() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_framebuffer())
}
define_prim!(hlp_gl_create_framebuffer, sdl_gl_create_framebuffer, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_program() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_program() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_program())
}
define_prim!(hlp_gl_create_program, sdl_gl_create_program, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_shader(a0: i32) -> i32;
}

/// `Pi_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_shader(a0: i32) -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_shader(a0))
}
define_prim!(hlp_gl_create_shader, sdl_gl_create_shader, "Pi_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_texture() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_texture() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_texture())
}
define_prim!(hlp_gl_create_texture, sdl_gl_create_texture, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_create_vertex_array() -> i32;
}

/// `P_Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_create_vertex_array() -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_create_vertex_array())
}
define_prim!(hlp_gl_create_vertex_array, sdl_gl_create_vertex_array, "P_Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_cull_face(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_cull_face(a0: i32) {
    ash_host_sdl_gl_cull_face(a0);
}
define_prim!(hlp_gl_cull_face, sdl_gl_cull_face, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_delete_shader(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_delete_shader(a0: *mut vdynamic) {
    ash_host_sdl_gl_delete_shader(unbox_i32(a0));
}
define_prim!(hlp_gl_delete_shader, sdl_gl_delete_shader, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_depth_func(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_depth_func(a0: i32) {
    ash_host_sdl_gl_depth_func(a0);
}
define_prim!(hlp_gl_depth_func, sdl_gl_depth_func, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_depth_mask(a0: i32);
}

/// `Pb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_depth_mask(a0: bool) {
    ash_host_sdl_gl_depth_mask(a0 as i32);
}
define_prim!(hlp_gl_depth_mask, sdl_gl_depth_mask, "Pb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_disable(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_disable(a0: i32) {
    ash_host_sdl_gl_disable(a0);
}
define_prim!(hlp_gl_disable, sdl_gl_disable, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_disable_vertex_attrib_array(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_disable_vertex_attrib_array(a0: i32) {
    ash_host_sdl_gl_disable_vertex_attrib_array(a0);
}
define_prim!(hlp_gl_disable_vertex_attrib_array, sdl_gl_disable_vertex_attrib_array, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_draw_elements(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_draw_elements(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_draw_elements(a0, a1, a2, a3);
}
define_prim!(hlp_gl_draw_elements, sdl_gl_draw_elements, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_enable(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_enable(a0: i32) {
    ash_host_sdl_gl_enable(a0);
}
define_prim!(hlp_gl_enable, sdl_gl_enable, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_enable_vertex_attrib_array(a0: i32);
}

/// `Pi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_enable_vertex_attrib_array(a0: i32) {
    ash_host_sdl_gl_enable_vertex_attrib_array(a0);
}
define_prim!(hlp_gl_enable_vertex_attrib_array, sdl_gl_enable_vertex_attrib_array, "Pi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_finish();
}

/// `P_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_finish() {
    ash_host_sdl_gl_finish();
}
define_prim!(hlp_gl_finish, sdl_gl_finish, "P_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_framebuffer_texture2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32);
}

/// `PiiiNii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_framebuffer_texture2d(a0: i32, a1: i32, a2: i32, a3: *mut vdynamic, a4: i32) {
    ash_host_sdl_gl_framebuffer_texture2d(a0, a1, a2, unbox_i32(a3), a4);
}
define_prim!(hlp_gl_framebuffer_texture2d, sdl_gl_framebuffer_texture2d, "PiiiNii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_attrib_location(a0: i32, a1: i32, a2: i32) -> i32;
}

/// `PNiOBi__i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_attrib_location(a0: *mut vdynamic, a1: *mut vstring) -> i32 {
    ash_host_sdl_gl_get_attrib_location(unbox_i32(a0), string_bytes(a1), string_length(a1))
}
define_prim!(hlp_gl_get_attrib_location, sdl_gl_get_attrib_location, "PNiOBi__i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_config_parameter(a0: i32) -> i32;
}

/// `Pi_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_config_parameter(a0: i32) -> i32 {
    ash_host_sdl_gl_get_config_parameter(a0)
}
define_prim!(hlp_gl_get_config_parameter, sdl_gl_get_config_parameter, "Pi_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_error() -> i32;
}

/// `P_i`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_error() -> i32 {
    ash_host_sdl_gl_get_error()
}
define_prim!(hlp_gl_get_error, sdl_gl_get_error, "P_i");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_program_parameter(a0: i32, a1: i32) -> i32;
}

/// `PNii_D`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_program_parameter(a0: *mut vdynamic, a1: i32) -> *mut vdynamic {
    ash_host_sdl_gl_get_program_parameter(unbox_i32(a0), a1) as *mut vdynamic
}
define_prim!(hlp_gl_get_program_parameter, sdl_gl_get_program_parameter, "PNii_D");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_shader_parameter(a0: i32, a1: i32) -> i32;
}

/// `PNii_D`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_shader_parameter(a0: *mut vdynamic, a1: i32) -> *mut vdynamic {
    ash_host_sdl_gl_get_shader_parameter(unbox_i32(a0), a1) as *mut vdynamic
}
define_prim!(hlp_gl_get_shader_parameter, sdl_gl_get_shader_parameter, "PNii_D");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_string(a0: i32) -> i32;
}

/// `Pi_B`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_string(a0: i32) -> *mut vbyte {
    ash_host_sdl_gl_get_string(a0) as *mut vbyte
}
define_prim!(hlp_gl_get_string, sdl_gl_get_string, "Pi_B");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_get_uniform_location(a0: i32, a1: i32, a2: i32) -> i32;
}

/// `PNiOBi__Ni`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_get_uniform_location(a0: *mut vdynamic, a1: *mut vstring) -> *mut vdynamic {
    box_i32(ash_host_sdl_gl_get_uniform_location(unbox_i32(a0), string_bytes(a1), string_length(a1)))
}
define_prim!(hlp_gl_get_uniform_location, sdl_gl_get_uniform_location, "PNiOBi__Ni");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_has_extension(a0: i32, a1: i32) -> i32;
}

/// `POBi__b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_has_extension(a0: *mut vstring) -> bool {
    ash_host_sdl_gl_has_extension(string_bytes(a0), string_length(a0)) != 0
}
define_prim!(hlp_gl_has_extension, sdl_gl_has_extension, "POBi__b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_init() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_init() -> bool {
    ash_host_sdl_gl_init() != 0
}
define_prim!(hlp_gl_init, sdl_gl_init, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_is_context_lost() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_is_context_lost() -> bool {
    ash_host_sdl_gl_is_context_lost() != 0
}
define_prim!(hlp_gl_is_context_lost, sdl_gl_is_context_lost, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_link_program(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_link_program(a0: *mut vdynamic) {
    ash_host_sdl_gl_link_program(unbox_i32(a0));
}
define_prim!(hlp_gl_link_program, sdl_gl_link_program, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_pixel_storei(a0: i32, a1: i32);
}

/// `Pii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_pixel_storei(a0: i32, a1: i32) {
    ash_host_sdl_gl_pixel_storei(a0, a1);
}
define_prim!(hlp_gl_pixel_storei, sdl_gl_pixel_storei, "Pii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_polygon_mode(a0: i32, a1: i32);
}

/// `Pii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_polygon_mode(a0: i32, a1: i32) {
    ash_host_sdl_gl_polygon_mode(a0, a1);
}
define_prim!(hlp_gl_polygon_mode, sdl_gl_polygon_mode, "Pii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_shader_source(a0: i32, a1: i32, a2: i32);
}

/// `PNiOBi__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_shader_source(a0: *mut vdynamic, a1: *mut vstring) {
    ash_host_sdl_gl_shader_source(unbox_i32(a0), string_bytes(a1), string_length(a1));
}
define_prim!(hlp_gl_shader_source, sdl_gl_shader_source, "PNiOBi__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_stencil_func_separate(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_stencil_func_separate(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_stencil_func_separate(a0, a1, a2, a3);
}
define_prim!(hlp_gl_stencil_func_separate, sdl_gl_stencil_func_separate, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_stencil_op_separate(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_stencil_op_separate(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_stencil_op_separate(a0, a1, a2, a3);
}
define_prim!(hlp_gl_stencil_op_separate, sdl_gl_stencil_op_separate, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32);
}

/// `PiiiiiiiiB_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_image2d(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: *mut vbyte) {
    ash_host_sdl_gl_tex_image2d(a0, a1, a2, a3, a4, a5, a6, a7, a8 as i32);
}
define_prim!(hlp_gl_tex_image2d, sdl_gl_tex_image2d, "PiiiiiiiiB_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_tex_parameteri(a0: i32, a1: i32, a2: i32);
}

/// `Piii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_tex_parameteri(a0: i32, a1: i32, a2: i32) {
    ash_host_sdl_gl_tex_parameteri(a0, a1, a2);
}
define_prim!(hlp_gl_tex_parameteri, sdl_gl_tex_parameteri, "Piii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_uniform1i(a0: i32, a1: i32);
}

/// `PNii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_uniform1i(a0: *mut vdynamic, a1: i32) {
    ash_host_sdl_gl_uniform1i(unbox_i32(a0), a1);
}
define_prim!(hlp_gl_uniform1i, sdl_gl_uniform1i, "PNii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_uniform4fv(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `PNiBii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_uniform4fv(a0: *mut vdynamic, a1: *mut vbyte, a2: i32, a3: i32) {
    ash_host_sdl_gl_uniform4fv(unbox_i32(a0), a1 as i32, a2, a3);
}
define_prim!(hlp_gl_uniform4fv, sdl_gl_uniform4fv, "PNiBii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_use_program(a0: i32);
}

/// `PNi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_use_program(a0: *mut vdynamic) {
    ash_host_sdl_gl_use_program(unbox_i32(a0));
}
define_prim!(hlp_gl_use_program, sdl_gl_use_program, "PNi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_vertex_attrib_pointer(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32);
}

/// `Piiibii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_vertex_attrib_pointer(a0: i32, a1: i32, a2: i32, a3: bool, a4: i32, a5: i32) {
    ash_host_sdl_gl_vertex_attrib_pointer(a0, a1, a2, a3 as i32, a4, a5);
}
define_prim!(hlp_gl_vertex_attrib_pointer, sdl_gl_vertex_attrib_pointer, "Piiibii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_gl_viewport(a0: i32, a1: i32, a2: i32, a3: i32);
}

/// `Piiii_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_gl_viewport(a0: i32, a1: i32, a2: i32, a3: i32) {
    ash_host_sdl_gl_viewport(a0, a1, a2, a3);
}
define_prim!(hlp_gl_viewport, sdl_gl_viewport, "Piiii_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_init_once() -> i32;
}

/// `P_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_init_once() -> bool {
    ash_host_sdl_init_once() != 0
}
define_prim!(hlp_init_once, sdl_init_once, "P_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_set_vsync(a0: i32);
}

/// `Pb_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_set_vsync(a0: bool) {
    ash_host_sdl_set_vsync(a0 as i32);
}
define_prim!(hlp_set_vsync, sdl_set_vsync, "Pb_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_create_ex(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32) -> i32;
}

/// `Piiiii_Xsdl_window_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_create_ex(a0: i32, a1: i32, a2: i32, a3: i32, a4: i32) -> *mut c_void {
    ash_host_sdl_win_create_ex(a0, a1, a2, a3, a4) as *mut c_void
}
define_prim!(hlp_win_create_ex, sdl_win_create_ex, "Piiiii_Xsdl_window_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_get_glcontext(a0: i32) -> i32;
}

/// `PXsdl_window__Xsdl_gl_`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_get_glcontext(a0: *mut c_void) -> *mut c_void {
    ash_host_sdl_win_get_glcontext(a0 as i32) as *mut c_void
}
define_prim!(hlp_win_get_glcontext, sdl_win_get_glcontext, "PXsdl_window__Xsdl_gl_");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_get_size(a0: i32, a1: i32, a2: i32);
}

/// `PXsdl_window_RiRi_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_get_size(a0: *mut c_void, a1: *mut i32, a2: *mut i32) {
    ash_host_sdl_win_get_size(a0 as i32, a1 as i32, a2 as i32);
}
define_prim!(hlp_win_get_size, sdl_win_get_size, "PXsdl_window_RiRi_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_render_to(a0: i32, a1: i32);
}

/// `PXsdl_window_Xsdl_gl__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_render_to(a0: *mut c_void, a1: *mut c_void) {
    ash_host_sdl_win_render_to(a0 as i32, a1 as i32);
}
define_prim!(hlp_win_render_to, sdl_win_render_to, "PXsdl_window_Xsdl_gl__v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_fullscreen(a0: i32, a1: i32) -> i32;
}

/// `PXsdl_window_i_b`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_fullscreen(a0: *mut c_void, a1: i32) -> bool {
    ash_host_sdl_win_set_fullscreen(a0 as i32, a1) != 0
}
define_prim!(hlp_win_set_fullscreen, sdl_win_set_fullscreen, "PXsdl_window_i_b");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_set_title(a0: i32, a1: i32);
}

/// `PXsdl_window_B_v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_set_title(a0: *mut c_void, a1: *mut vbyte) {
    ash_host_sdl_win_set_title(a0 as i32, a1 as i32);
}
define_prim!(hlp_win_set_title, sdl_win_set_title, "PXsdl_window_B_v");

#[link(wasm_import_module = "env")]
extern "C" {
    fn ash_host_sdl_win_swap_window(a0: i32);
}

/// `PXsdl_window__v`
///
/// # Safety
/// Called by the VM through the resolver below, with the arguments the
/// signature above declares.
#[no_mangle]
pub unsafe extern "C" fn sdl_win_swap_window(a0: *mut c_void) {
    ash_host_sdl_win_swap_window(a0 as i32);
}
define_prim!(hlp_win_swap_window, sdl_win_swap_window, "PXsdl_window__v");
